// ============================================================
// BODY TRACKER for AI Dungeon: LIBRARY tab (Whitney, custom player)
// GENERATED by build.js from src/ and presets/whitney_custom.js. Edit those, not this file.
// Paste this whole file into the Library tab.
// ============================================================

// ---------- CONFIG: change these freely ----------
const CFG = {
  PACE: 3,               // muscle growth speed. 1 = realistic, 3 = fast (game pace)
  PATTERN: 'pear',       // where new fat lands at the start: pear | apple | even
  LOOK: 'curvy',         // what Charisma rewards: curvy | athletic | soft | off  (change in game with :look)
  SUPPORT: true,         // supportive bra halves sag build-up (change in game with :support on/off)
  ACTIVITY: 1.35,        // 1.2 sedentary, 1.35 light, 1.55 active
  KCAL_PER_KG: 7700,     // energy in 1 kg of body tissue
  FAT_GAIN: 0.75,        // share of a surplus that becomes fat (the rest is lean tissue)
  FAT_LOSS: 0.8,         // share of a deficit that comes from fat
  TAG_PLACE: 'note',     // where the hidden-tag reminder goes: 'note' (Author's Note, default, least likely to be echoed) | 'front' (last line of the context, strongest)
  TAG_HELP: true,        // tell the AI about the hidden tags at the end of the context (turn off to save tokens)
  DESCRIBE: true,        // add a 'Look:' line with shape and size adjectives to the AI's note (edit the words in LOOK_WORDS below)
  FUZZY: true,           // forgive typos and odd wording when spotting actions in what you type
  NPC_MAX: 2,            // other tracked characters go into the AI's note only while their name is in the recent story, at most this many
  HIDE_PLAYER: false,   // true = you are not tracked, only the characters below (unnamed commands and tags then go to the first one)
  CHARACTERS: [],       // characters that exist from the first turn: { name, start: { weight: 70, ... }, pattern, look, bonus: { cha: 2 } } (see presets/)
  SILLY: false,          // game-pace preset: PACE 6 (SILLY_PACE), FAT_GAIN 0.9 (SILLY_FAT_GAIN), lazy meals, and fat gain/loss is scaled by the pace so a few days show. :pace n still overrides the pace. Off = everything back to the normal values
  SILLY_PACE: 6,
  SILLY_FAT_GAIN: 0.9,   // share of a surplus that becomes fat under SILLY (more forgiving: less of it is lean)
  PLAYER: null,          // seeds YOUR sheet once, on the first turn: { name, start: { ... }, pattern, look, bonus: {}, set: { dex: 12 } }. HIDE_PLAYER must be false to see it
  PLACEHOLDERS: false,   // true = on the first turn, seed YOUR sheet from state.placeholders (name, height, weight, build, activity, chest). Only the custom preset turns it on
  PLAYER_CARD: false,    // true = a "Player setup" story card (name= height= weight= ...) fills in your own sheet when you edit it. Only the custom preset turns it on
  PROBE: false,         // true = the :probe command exists (writes a story card describing what the hooks receive). Only the custom preset turns it on
  LAZY: false,          // true = typed and narrated meals use flat amounts: meal 700, snack 300, sweet 400 kcal, scaled by size words (massive x1.5, small x0.5). :eat stays exact
  YOU_NAME: '',          // who "you" means in the AI's narration when your own sheet is hidden, e.g. 'Rue'. Empty = "you" is not attributed
  AUTO: true,           // also spot eating, exercise and sleeping in what YOU type, so tracking works even if the AI never writes tags
  STATUS: 'commands',    // add a status line to the reply: 'off' | 'commands' (commands and spotted actions) | 'always'
  CARD_READBACK: false,  // read hand edits of the Body sheet story card back into the tracker
  // starting body (measurements in cm, weight in kg, gland = glandular tissue in cc per breast)
  START: { height: 165, weight: 60, bodyfat: 26, underbust: 74, bust: 89, waist: 70, hips: 95, arm: 27, thigh: 55, gland: 90, potential: 150 },
  // which optional systems the Author's Note tells the AI about (turn one off to save tokens)
  FEATURES: { milk: true, mana: true, curses: true }
}
const CARD_TYPE = 'Body sheet'
const CARD_KEYS = 'bodysheet'   // nothing in the story says this, so the card never costs context

// Preset: Whitney scenario with a custom player (Scenario 2). Applied right after the config.
// You are not Rue: you get the default sheet (set it with :set height 170, :set weight 60 ... or :sheet), and an unnamed
// "You order ..." in the AI's reply, or anything you do unnamed, goes to that player sheet. No player seed, no YOU_NAME.
CFG.SILLY = true         // game pace: PACE 6, more forgiving fat gain, lazy meals (see the config). :pace n still overrides
CFG.HIDE_PLAYER = false  // you are tracked too
CFG.PLACEHOLDERS = true  // the character-creation answers (state.placeholders) set up your sheet on the first turn
CFG.PLAYER_CARD = true   // a "Player setup" story card: fill in name= height= weight= ... to set up your own sheet
CFG.PROBE = true        // :probe writes a story card showing what the hooks receive (info, state keys, history). Delete the card when done
CFG.CHARACTERS = [
  { name: 'Whitney', pattern: 'pear', look: 'curvy', bonus: { cha: 2 },   // proud and charismatic
    start: { height: 196, weight: 105, bodyfat: 34, underbust: 96, bust: 116, waist: 100, hips: 128, arm: 36, thigh: 75, gland: 150, potential: 225 } }
]

// ---------- constants ----------
const REGIONS = ['chest', 'arms', 'core', 'glutes', 'legs']
const AB = ['str', 'dex', 'con', 'int', 'wis', 'cha']
const MEAS = ['underbust', 'bust', 'waist', 'hips', 'arm', 'thigh']
const LIMITS = { height: [50, 230], weight: [20, 300], bodyfat: [4, 70], underbust: [40, 200], bust: [45, 250], waist: [30, 250], hips: [45, 250], arm: [15, 70], thigh: [30, 110] }
const LABEL = { height: 'Height', weight: 'Weight', bodyfat: 'Body fat', underbust: 'Underbust', bust: 'Bust', waist: 'Waist', hips: 'Hips', arm: 'Upper arm', thigh: 'Thigh', gland: 'Glandular tissue', sag: 'Sag', potential: 'Glandular potential' }
const UNIT = { height: 'cm', weight: 'kg', bodyfat: '%', underbust: 'cm', bust: 'cm', waist: 'cm', hips: 'cm', arm: 'cm', thigh: 'cm', gland: 'cc each', sag: '', potential: 'cc each' }
const STAT_KEYS = Object.keys(LIMITS).concat(AB, ['gland', 'sag', 'potential'])
const RWORD = { chest: 'chest', arms: 'arms', core: 'midsection', glutes: 'glutes', legs: 'legs' }
const MUS_START = { chest: 2.0, arms: 3.2, core: 3.5, glutes: 3.8, legs: 9.5 }   // kg at 60 kg body weight
const PATTERNS = {
  pear: { chest: .12, arms: .12, core: .22, glutes: .24, legs: .30 },
  apple: { chest: .16, arms: .12, core: .38, glutes: .16, legs: .18 },
  even: { chest: .20, arms: .20, core: .20, glutes: .20, legs: .20 }
}
// cm change per kg of regional fat / muscle
const COEF = {
  underbust: { fat: { chest: 2.0, core: 0.7 }, mus: { chest: 3.0 } },
  waist: { fat: { core: 4.5 }, mus: { core: 0.8 } },
  hips: { fat: { glutes: 2.6, legs: 0.6 }, mus: { glutes: 2.0, legs: 0.5 } },
  arm: { fat: { arms: 2.5 }, mus: { arms: 4.5 } },
  thigh: { fat: { legs: 2.2 }, mus: { legs: 2.2 } }
}
const MANA_DECAY = 0.5, MILK_KCAL_PER_ML = 0.8
const MANA_PER_KG = { mus: 8, fat: 3, gland: 150 }   // mana stored per kg of muscle, fat and glandular tissue
const CURSES = ['hunger', 'leech', 'forced', 'bias']
const BREAST_FAT_SHARE = 0.25, FAT_G_PER_CC = 0.92, CONN_CC = 20
const CUPS = ['AAA', 'AA', 'A', 'B', 'C', 'D', 'DD', 'E', 'F', 'G', 'H', 'I', 'J', 'K']
const LOOKS = ['curvy', 'athletic', 'soft', 'off']
const PARTS = { chest: 'chest', bust: 'chest', breast: 'chest', breasts: 'chest', arm: 'arms', arms: 'arms', core: 'core', waist: 'core', stomach: 'core', belly: 'core', abs: 'core', glute: 'glutes', glutes: 'glutes', hip: 'glutes', hips: 'glutes', leg: 'legs', legs: 'legs', thigh: 'legs', thighs: 'legs', body: 'all', all: 'all' }
const PART_RE = '(chest|bust|breasts?|arms?|core|waist|stomach|belly|abs|glutes?|hips?|legs?|thighs?|body|all)'

// ---------- small helpers ----------
// effective settings (SILLY bundles lazy meals, a faster pace and more forgiving fat gain)
const lazyOn = () => !!(CFG.LAZY || CFG.SILLY)
const paceOf = (s) => (s.paceSet ? s.pace : (CFG.SILLY ? CFG.SILLY_PACE : CFG.PACE))   // :pace n sets s.pace and s.paceSet
const fatGain = () => (CFG.SILLY ? CFG.SILLY_FAT_GAIN : CFG.FAT_GAIN)
const r1 = (v) => Math.round(v * 10) / 10
const r2 = (v) => Math.round(v * 100) / 100
const clampN = (v, a, b) => Math.min(b, Math.max(a, v))
const sum = (o) => REGIONS.reduce((t, r) => t + o[r], 0)
const zero = () => ({ chest: 0, arms: 0, core: 0, glutes: 0, legs: 0 })
const copy = (o) => JSON.parse(JSON.stringify(o))
const fmt = (n) => Math.round(n).toString().replace(/\B(?=(\d{3})+(?!\d))/g, ',')
const sgn = (v) => (v >= 0 ? '+' : '')

// ---------- state ----------
const newBT = (startOverride, opts) => {
  opts = opts || {}
  const st = Object.assign({}, CFG.START, startOverride || {})
  const pattern = opts.pattern || CFG.PATTERN
  const P = PATTERNS[pattern] || PATTERNS.pear, k = st.weight / 60
  const s = {
    name: opts.name || '', start: st, pattern: pattern,
    day: 1, eaten: null, burned: 0, train: zero(), height: st.height, fat: {}, mus: {}, adj: {},
    bonus: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 }, gland: st.gland, sag: 0,
    fuelLog: [], auto: {}, lastDayAt: 0, support: CFG.SUPPORT, look: opts.look || CFG.LOOK, pace: CFG.PACE,
    lact: { on: false, stored: 0, sup: 0, demand: 0, drained: 0, lowDays: 0 }, mana: zero(),
    curses: { hunger: false, leech: '', forced: false, bias: '' }, glandMax: st.potential, gland0: st.gland
  }
  const fatT = st.weight * st.bodyfat / 100
  REGIONS.forEach((r) => { s.fat[r] = fatT * P[r]; s.mus[r] = MUS_START[r] * k * (opts.muscle || 1) })   // muscle: starting muscle multiplier (1 = the usual)
  s.muscleMul = opts.muscle || 1
  if (opts.activity) s.activity = opts.activity   // this sheet's own activity factor (otherwise CFG.ACTIVITY)
  s.fat0 = copy(s.fat)
  s.mus0 = copy(s.mus)
  s.other = st.weight - fatT - sum(s.mus)
  MEAS.forEach((m) => { s.adj[m] = 0 })
  s.bustA = (st.bust - st.underbust) / Math.pow(volume(s).total, 0.4)
  s.volPrev = volume(s).tissue
  return s
}
function upgradeBT(s) {   // lets an adventure started with an older version keep working
  if (!s.start) s.start = Object.assign({}, CFG.START)
  if (!s.pattern) s.pattern = CFG.PATTERN
  if (s.name === undefined) s.name = ''
  if (!s.auto) s.auto = {}
  if (s.lastDayAt === undefined) s.lastDayAt = 0
  if (!s.lact) s.lact = { on: false, stored: 0, sup: 0, demand: 0, drained: 0, lowDays: 0 }
  if (!s.mana) s.mana = zero()
  if (!s.curses) s.curses = { hunger: false, leech: '', forced: false, bias: '' }
  if (s.glandMax === undefined) s.glandMax = s.start.potential
  if (s.gland0 === undefined) s.gland0 = s.start.gland
}
function newPlayer() {   // your own sheet: the defaults, or CFG.PLAYER (a named character with their own starting body)
  const P = CFG.PLAYER
  if (!P) return newBT()
  const s = newBT(P.start, { name: P.name, pattern: P.pattern, look: P.look })
  Object.keys(P.bonus || {}).forEach((b) => { s.bonus[b] = P.bonus[b] })
  Object.keys(P.set || {}).forEach((k) => { applyOp(s, k, '=', P.set[k]) })   // same as :set dex 13
  return s
}
const initBT = () => {
  if (!state.bt) state.bt = newBT(); else upgradeBT(state.bt)
  if (!state.npcs) state.npcs = {}
  Object.keys(state.npcs).forEach((k) => upgradeBT(state.npcs[k]))
  if (!state.bt_seeded) {   // preset characters are created once, on the first turn
    state.bt_seeded = true
    ;(CFG.CHARACTERS || []).forEach((c) => {
      const k = c.name.toLowerCase()
      if (state.npcs[k]) return
      state.npcs[k] = newBT(c.start, { name: c.name, pattern: c.pattern, look: c.look })
      Object.keys(c.bonus || {}).forEach((b) => { state.npcs[k].bonus[b] = c.bonus[b] })
    })
    if (CFG.PLAYER) state.bt = newPlayer()
    if (CFG.HIDE_PLAYER) state.bt_hideYou = true
  }
  if (state.bt && state.bt.name && !CFG.YOU_NAME) CFG.YOU_NAME = state.bt.name   // YOU_NAME follows the player's name
}

// ---------- several characters: you plus anyone added with :sheet add ----------
const esc = (str) => str.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
const npcKeys = () => Object.keys(state.npcs || {})
function namesIn(text) {   // keys of tracked characters mentioned in the text
  const out = []
  npcKeys().forEach((k) => {
    const nm = state.npcs[k].name || k
    if (new RegExp("\\b" + esc(nm) + "(?:'s)?\\b", 'i').test(text)) out.push(k)
  })
  return out
}
const sheetOf = (key) => (key ? state.npcs[key] : state.bt)
const nameOf = (key) => (sheetOf(key) && sheetOf(key).name) || ''   // '' for an unnamed player sheet
const playerName = () => {   // your own sheet's name (Rue), unless a named NPC already has it
  const n = (state.bt && state.bt.name) || CFG.YOU_NAME || ''
  return n && !(state.npcs || {})[n.toLowerCase()] ? n : ''
}
function whoIn(text) {   // like namesIn, plus '' (your sheet) when the text names the player ("Rue")
  const out = namesIn(text), pn = playerName()
  if (pn && !state.bt_hideYou && new RegExp('\\b' + esc(pn) + "(?:'s)?\\b", 'i').test(text)) out.push('')
  return out
}
const SHARE_RE = /\b(?:share|shares|sharing|shared|split|splits|splitting|together|halves)\b/i
const turnNo = () => (typeof info !== 'undefined' && info && typeof info.actionCount === 'number' && info.actionCount > 0 ? info.actionCount : (typeof history !== 'undefined' && history ? history.length : 0))
const defKey = () => (state.bt_hideYou && npcKeys().length ? npcKeys()[0] : '')   // who unnamed commands and tags mean
const labelOf = (key) => (key ? state.npcs[key].name + ': ' : '')
function recentText(text) {
  let t = text || ''
  if (typeof history !== 'undefined' && history && history.length) t += ' ' + history.slice(-3).map((a) => (a && a.text) || '').join(' ')
  return t
}
function resetAuto() {
  state.bt.auto = {}
  npcKeys().forEach((k) => { state.npcs[k].auto = {} })
}
function dayAll(n) {   // time passes for everyone
  const notes = [advanceDays(state.bt, n)]
  npcKeys().forEach((k) => { notes.push(state.npcs[k].name + ': ' + advanceDays(state.npcs[k], n)) })
  return notes.join(' | ')
}

// undo / retry support: the tracker is snapshotted once per turn, keyed by where the story is
// (the action count plus a fingerprint of the last few actions). If we come back to a moment we
// already saw, the tracker goes back to how it was then, so a retry or undo is never counted twice.
const snap = () => JSON.stringify({ bt: state.bt, npcs: state.npcs || {} })
const restore = (str) => {
  const o = JSON.parse(str)
  if (o && o.bt !== undefined) { state.bt = o.bt; state.npcs = o.npcs || {} } else state.bt = o   // older snapshots held just the player
}
const hashStr = (str) => {
  let x = 5381
  for (let i = 0; i < str.length; i++) x = ((x << 5) + x + str.charCodeAt(i)) | 0
  return (x >>> 0).toString(36)
}
function slotKey() {
  const c = (typeof info !== 'undefined' && info && typeof info.actionCount === 'number') ? info.actionCount : ''
  let tail = ''
  if (typeof history !== 'undefined' && history && history.length) {
    tail = history.slice(-4).map((a) => (a && a.text) || '').join('\u0002')
  }
  if (c === '' && tail === '') return ''   // nothing tells one turn from another, so skip snapshots
  return c + ':' + hashStr(tail)
}
function takeSlot(name) {
  if (!Array.isArray(state[name])) state[name] = []
  const list = state[name], key = slotKey()
  if (key === '') return
  for (let i = list.length - 1; i >= 0; i--) {
    if (list[i][0] === key) { restore(list[i][1]); list.length = i; break }   // been here before: go back to that moment
  }
  list.push([key, snap()])
  while (list.length > 40) list.shift()
}

// ---------- body model ----------
function volume(s) {   // breast volume per breast, in cc
  const fat = s.fat.chest * BREAST_FAT_SHARE * 1000 / FAT_G_PER_CC / 2
  const tissue = fat + s.gland + CONN_CC, milk = s.lact.stored / 2
  return { fat: fat, gland: s.gland, conn: CONN_CC, milk: milk, tissue: tissue, total: tissue + milk }
}
function chestCalc(s) {
  const V = volume(s), g = V.gland / V.tissue
  const musR = s.mus.chest / s.mus0.chest
  const firm = clampN(60 + 80 * (g - 0.25) + 10 * (musR - 1) / 0.6 - 12 * s.sag, 0, 100)
  return { V: V, g: g, firm: firm }
}
const firmWord = (f) => (f >= 70 ? 'firm' : f >= 45 ? 'moderately firm' : 'soft')
const sagWord = (x) => (x < 0.4 ? 'no sag' : x < 1.2 ? 'slight sag' : x < 2.2 ? 'moderate sag' : 'significant sag')

// ---- milk ----
const milkCap = (s) => s.gland * 2 * 1.5                          // ml both breasts hold when full
const milkRateMax = (s) => 750 * Math.pow(s.gland / 150, 0.8)     // ml per day at full supply, both breasts
const milkCost = (s) => milkRateMax(s) * s.lact.sup * MILK_KCAL_PER_ML
const glandCeil = (s) => s.glandMax * (s.curses.forced ? 1.5 : 1)
const lactActive = (s) => s.lact.on || s.curses.forced
function drainMilk(s, req) {
  const got = Math.min(s.lact.stored, req)
  s.lact.stored -= got
  s.lact.drained += req   // asking counts as demand even if there is less to take
  return got
}
// ---- mana ----
function manaCap(s, r) {
  let c = s.mus[r] * MANA_PER_KG.mus + s.fat[r] * MANA_PER_KG.fat
  if (r === 'chest') c += s.gland * 2 / 1000 * MANA_PER_KG.gland
  return c
}
const fillOf = (s, rs) => {
  let m = 0, c = 0
  rs.forEach((r) => { m += s.mana[r]; c += manaCap(s, r) })
  return c ? m / c : 0
}
function manaInfuse(s, target, n) {
  const rs = target === 'all' ? REGIONS : [target]
  const free = {}
  let tot = 0
  rs.forEach((r) => { free[r] = Math.max(0, manaCap(s, r) - s.mana[r]); tot += free[r] })
  const add = Math.min(n, tot)
  if (tot > 0) rs.forEach((r) => { s.mana[r] += add * free[r] / tot })
  return { added: add, wasted: n - add }
}
function manaSpend(s, target, n) {
  const rs = target === 'all' ? REGIONS : [target]
  let tot = 0
  rs.forEach((r) => { tot += s.mana[r] })
  const spent = Math.min(n, tot)
  if (tot > 0) rs.forEach((r) => { s.mana[r] -= spent * s.mana[r] / tot })
  return { spent: spent, short: n - spent }
}
function setCurse(s, op, name, region) {
  const on = op === 'add'
  if (name === 'hunger') s.curses.hunger = on
  else if (name === 'forced') s.curses.forced = on
  else if (name === 'leech') s.curses.leech = on ? (region || 'chest') : ''
  else if (name === 'bias') s.curses.bias = on ? (region || 'chest') : ''
  return (on ? 'Cursed: ' : 'Curse lifted: ') + name + (on && region ? ' (' + region + ')' : '')
}

function measures(s) {
  const fatT = sum(s.fat), musT = sum(s.mus), weight = fatT + musT + s.other
  const m = { height: s.height, weight: weight, bodyfat: fatT / weight * 100 }
  MEAS.forEach((k) => {
    if (k === 'bust') return
    let v = s.start[k] + s.adj[k]
    const c = COEF[k]
    for (const r in c.fat) v += c.fat[r] * (s.fat[r] - s.fat0[r])
    for (const r in c.mus) v += c.mus[r] * (s.mus[r] - s.mus0[r])
    m[k] = clampN(v, LIMITS[k][0], LIMITS[k][1])
  })
  // bust = underbust plus the cup difference, which comes from breast volume
  m.bust = clampN(m.underbust + s.bustA * Math.pow(volume(s).total, 0.4) + s.adj.bust, LIMITS.bust[0], LIMITS.bust[1])
  return m
}
function cup(m) {
  const idx = Math.round((m.bust - m.underbust - 7.5) / 2.5)
  return (Math.round(m.underbust / 5) * 5) + CUPS[clampN(idx, 0, CUPS.length - 1)]
}

// Ability scores. Body based: STR, DEX, CON, CHA. Story based: INT, WIS.
function abilities(s, m) {
  const H2 = Math.pow(m.height / s.start.height, 2), bf = m.bodyfat
  const wm = s.mus.legs + s.mus.glutes + 1.3 * s.mus.arms + 1.2 * s.mus.chest + 0.9 * s.mus.core
  const wRatio = wm / (23.01 * H2 * (s.start.weight / 60))
  const coreLeg = (s.mus.core / s.mus0.core + s.mus.legs / s.mus0.legs) / 2
  const musRatio = sum(s.mus) / (22 * H2 * (s.start.weight / 60))
  const inRange = bf >= 18 && bf <= 30
  const dist = bf < 18 ? 18 - bf : bf > 30 ? bf - 30 : 0
  const n = s.fuelLog.length, steady = n ? s.fuelLog.reduce((a, c) => a + c, 0) / n : 0
  const raw = {}
  raw.str = 10 + (wm - 23.01 * H2 * (s.start.weight / 60)) * 0.6
  raw.dex = 10 + (26 - clampN(bf, 12, 45)) * 0.25 + 2 * (coreLeg - 1) / 0.6
  raw.con = 10 + (inRange ? 1 : -Math.min(5, dist * 0.3)) + (n >= 3 ? (steady - 0.5) * 3 : 0) + (musRatio - 1) * 3
  raw.int = 10
  raw.wis = 10
  const whr = m.waist / m.hips
  let shape = 0
  if (s.look === 'curvy') shape = 1 - Math.abs(whr - 0.68) / 0.15
  else if (s.look === 'athletic') shape = (clampN((wRatio - 1) / 0.3, -1, 1) + clampN(1 - Math.abs(bf - 20) / 15, -1, 1)) / 2
  else if (s.look === 'soft') shape = 1 - Math.abs(bf - 32) / 12
  shape = clampN(shape, -1, 1)
  raw.cha = 10 + 2 * shape + ((raw.str + raw.dex + raw.con) / 3 - 10) * 0.2
  // mana gives temporary bonuses; full breasts cost Dexterity
  const mb = { str: 3 * fillOf(s, ['arms', 'chest', 'legs']), dex: 3 * fillOf(s, ['core', 'glutes']), con: 2 * fillOf(s, REGIONS), int: 2 * fillOf(s, REGIONS), wis: 2 * fillOf(s, REGIONS), cha: 0 }
  const fillMilk = s.lact.stored / Math.max(1, milkCap(s))
  const pen = { dex: fillMilk > 0.95 ? 2 : fillMilk > 0.8 ? 1 : 0 }
  const out = {}
  AB.forEach((k) => {
    const perm = raw[k] + s.bonus[k], total = perm + mb[k] - (pen[k] || 0)
    out[k] = { perm: perm, total: total, score: clampN(Math.round(total), 3, 20) }
  })
  return out
}
const statLine = (a) => AB.map((k) => k.toUpperCase() + ' ' + a[k].score).join(', ')

// ---------- energy and growth ----------
const leanMass = (s, m) => m.weight - sum(s.fat)
const need = (s, m, burn) => {
  const base = (370 + 21.6 * leanMass(s, m)) * (s.activity || CFG.ACTIVITY)
  return Math.round(base + (burn || 0) + milkCost(s) + (s.curses.hunger ? base * 0.25 : 0))
}

// where fat lands (gain) or leaves (loss: the stubborn areas empty last)
function distWeights(s, gain) {
  const p = PATTERNS[s.pattern] || PATTERNS.pear
  let w = {}
  if (gain) w = Object.assign({}, p)
  else {
    let tot = 0
    REGIONS.forEach((r) => { w[r] = 1 / p[r]; tot += w[r] })
    REGIONS.forEach((r) => { w[r] /= tot })
  }
  const b = s.curses.bias   // growth bias curse: new fat lands here, and leaves here last
  if (b) {
    if (gain) REGIONS.forEach((r) => { w[r] = 0.4 * w[r] + (r === b ? 0.6 : 0) })
    else {
      w[b] *= 0.3
      let t = 0
      REGIONS.forEach((r) => { t += w[r] })
      REGIONS.forEach((r) => { w[r] /= t })
    }
  }
  return w
}

function advanceDay(s, useLogged) {
  const m0 = measures(s)
  const eaten = useLogged ? s.eaten : null
  const burned = useLogged ? s.burned : 0
  const nd = need(s, m0, burned)
  const net = eaten === null ? 0 : eaten - nd
  if (eaten !== null) {
    s.fuelLog.push(Math.abs(eaten / nd - 1) <= 0.25 ? 1 : 0)
    if (s.fuelLog.length > 14) s.fuelLog.shift()
  }
  const scale = CFG.SILLY ? paceOf(s) : 1   // SILLY: body change (fat and lean, gain and loss) is scaled by the pace, so a few days show. :pace n changes it
  const deltaKg = net / CFG.KCAL_PER_KG * scale
  const share = net >= 0 ? fatGain() : CFG.FAT_LOSS
  const fatD = deltaKg * share
  const w = distWeights(s, fatD >= 0)
  REGIONS.forEach((r) => { s.fat[r] = Math.max(0.3, s.fat[r] + fatD * w[r]) })
  s.other = Math.max(8, s.other + deltaKg * (1 - share))

  // muscle grows where you trained, and shrinks a little elsewhere in a hard deficit
  const fuel = eaten === null ? 0.6 : net >= 200 ? 1 : net >= -300 ? 0.6 : 0.25
  const musBefore = sum(s.mus)
  const grew = []
  REGIONS.forEach((r) => {
    const t = useLogged ? s.train[r] : 0
    if (t > 0) {
      const room = Math.max(0, 1 - (s.mus[r] / s.mus0[r] - 1) / 0.6)
      const g = s.mus[r] * 0.0011 * t * fuel * room * paceOf(s)
      s.mus[r] += g
      if (g > 0) grew.push(RWORD[r])
    } else if (net < -500) {
      s.mus[r] -= s.mus[r] * 0.0004 * (-net / 500)
    }
  })
  const musD = sum(s.mus) - musBefore

  // milk: supply follows demand, storage fills, and full breasts leak and slow down
  const L = s.lact, rateMax = milkRateMax(s), capT = milkCap(s)
  let leaked = 0
  if (lactActive(s)) {
    L.demand = 0.7 * L.demand + 0.3 * L.drained
    let target = clampN(L.demand / rateMax, 0.15, 1)
    if (s.curses.forced) target = Math.max(target, 0.6)
    L.sup += (target - L.sup) * 0.25
  } else {
    L.sup *= 0.85
    L.demand *= 0.7
    L.stored *= 0.8   // unused milk is slowly reabsorbed
    if (L.sup < 0.01) L.sup = 0
    if (L.stored < 0.5) L.stored = 0
  }
  const prod = rateMax * L.sup
  L.stored += prod
  if (L.stored > capT) { leaked = L.stored - capT; L.stored = capT; L.sup *= 0.92 }
  // glandular tissue adapts: grows under sustained high demand, shrinks back after a week of low demand
  const ratio = rateMax > 0 ? L.demand / rateMax : 0
  if (lactActive(s) && ratio > 0.9 && s.gland < glandCeil(s)) s.gland = Math.min(glandCeil(s), s.gland * (1 + 0.004 * paceOf(s)))
  L.lowDays = ((lactActive(s) && ratio >= 0.3) || s.curses.forced) ? 0 : L.lowDays + 1
  if (L.lowDays >= 7 && s.gland > s.gland0) s.gland = Math.max(s.gland0, s.gland * 0.993)
  L.drained = 0

  // mana fades fast; a leech curse refills one area and turns overflow into lasting tissue
  REGIONS.forEach((r) => { s.mana[r] *= (1 - MANA_DECAY) })
  if (s.curses.leech) {
    const r = s.curses.leech, cap = manaCap(s, r), add = cap * 0.7, space = cap - s.mana[r]
    if (add <= space) s.mana[r] += add
    else {
      s.mana[r] = cap
      const over = add - space
      if (r === 'chest') s.gland = Math.min(600, s.gland + over * 0.05)
      else s.mus[r] += over * 0.0008
    }
  }

  // strain on the breast tissue: fast tissue change, heavy volume and full breasts all add sag
  const v1 = volume(s)
  const rate = Math.abs(v1.tissue - s.volPrev) / s.volPrev * 100
  const heavy = Math.max(0, v1.total - 500) / 500
  const fillM = L.stored / Math.max(1, capT)
  const engorge = fillM > 0.8 ? (fillM - 0.8) / 0.2 * 0.02 : 0
  s.sag = clampN(s.sag + (0.015 * heavy + 0.02 * rate + engorge) * (s.support ? 0.5 : 1), 0, 3)
  s.volPrev = v1.tissue

  s.day++
  s.eaten = null
  s.burned = 0
  s.train = zero()

  const milkTxt = lactActive(s) ? ', milk +' + Math.round(prod) + ' ml' + (leaked > 1 ? ' (' + Math.round(leaked) + ' leaked)' : '') : ''
  if (eaten === null) return 'Day ' + (s.day - 1) + ': nothing logged, assumed maintenance' + milkTxt
  let rep = 'Day ' + (s.day - 1) + ': ate ' + fmt(eaten) + ', needed ' + fmt(nd) + ' (' + sgn(net) + fmt(net) + ' kcal)'
  if (Math.abs(musD) >= 0.005) rep += ', muscle ' + sgn(musD) + r2(musD) + ' kg' + (grew.length ? ' in ' + grew.join(', ') : '')
  return rep + milkTxt
}
function advanceDays(s, n) {
  n = clampN(Math.round(n), 1, 30)
  let rep = advanceDay(s, true)
  for (let i = 1; i < n; i++) advanceDay(s, false)
  if (n > 1) rep += ' (+' + (n - 1) + ' more days at maintenance)'
  return rep
}

// ---------- setting values ----------
function currentValue(s, k) {
  if (AB.indexOf(k) >= 0) return abilities(s, measures(s))[k].perm
  if (k === 'gland') return s.gland
  if (k === 'potential') return s.glandMax
  if (k === 'sag') return s.sag
  return measures(s)[k]
}
function setValue(s, k, v) {
  if (AB.indexOf(k) >= 0) { s.bonus[k] += v - currentValue(s, k); return }
  if (k === 'gland') { s.gland = clampN(v, 0, 600); return }
  if (k === 'potential') { s.glandMax = clampN(v, 0, 600); return }
  if (k === 'sag') { s.sag = clampN(v, 0, 3); return }
  v = clampN(v, LIMITS[k][0], LIMITS[k][1])
  const m = measures(s)
  if (k === 'height') s.height = v
  else if (k === 'weight') s.other = Math.max(5, s.other + (v - m.weight))
  else if (k === 'bodyfat') {
    const d = m.weight * v / 100 - sum(s.fat)
    const w = distWeights(s, d >= 0)
    REGIONS.forEach((r) => { s.fat[r] = Math.max(0.2, s.fat[r] + d * w[r]) })
    s.other = Math.max(5, s.other - d)
  } else s.adj[k] += v - m[k]
}
function applyOp(s, k, op, n) {
  const old = currentValue(s, k)
  setValue(s, k, op === '+' ? old + n : op === '-' ? old - n : n)
  const now = currentValue(s, k)
  if (AB.indexOf(k) >= 0) return k.toUpperCase() + ' ' + Math.round(old) + ' to ' + Math.round(now)
  return (LABEL[k] || k) + ' ' + r1(old) + ' to ' + r1(now) + (UNIT[k] ? ' ' + UNIT[k] : '')
}

function doMana(s, sign, n, region) {
  n = Math.min(n, 2000)
  if (sign === '+') {
    const r = manaInfuse(s, region, n)
    return 'Mana +' + Math.round(r.added) + (region === 'all' ? '' : ' ' + region) + (r.wasted > 0.5 ? ' (' + Math.round(r.wasted) + ' wasted)' : '')
  }
  const r = manaSpend(s, region, n)
  return 'Mana -' + Math.round(r.spent) + (region === 'all' ? '' : ' ' + region) + (r.short > 0.5 ? ' (short by ' + Math.round(r.short) + ')' : '')
}

// ---------- tags written by the AI ----------
function parseOne(t) {   // one tag such as "[ate 600]" -> an event, or null if it is not ours
  let m = t.match(/^\[\s*train\s+(chest|arms|core|glutes|legs)(?:\s+([1-3]))?\s*\]$/i)
  if (m) return { type: 'train', r: m[1].toLowerCase(), n: m[2] ? parseInt(m[2], 10) : 2 }
  m = t.match(/^\[\s*curse\s+(add|remove)\s+(hunger|leech|forced|bias)(?:\s+(chest|arms|core|glutes|legs))?\s*\]$/i)
  if (m) return { type: 'curse', op: m[1].toLowerCase(), name: m[2].toLowerCase(), r: m[3] ? m[3].toLowerCase() : '' }
  m = t.match(/^\[\s*lactating\s+(on|off)\s*\]$/i)
  if (m) return { type: 'lact', on: m[1].toLowerCase() === 'on' }
  m = t.match(/^\[\s*mana\s*([+\-])\s*(\d+(?:\.\d+)?)(?:\s+(chest|arms|core|glutes|legs))?\s*\]$/i)
  if (m) return { type: 'mana', sign: m[1], n: parseFloat(m[2]), r: m[3] ? m[3].toLowerCase() : 'all' }
  m = t.match(/^\[\s*(\w+)\s*([+\-=]?)\s*(\d+(?:\.\d+)?)?\s*(?:cm|kg|kcal|cc|ml|%)?\s*\]$/i)
  if (m) {
    const k = m[1].toLowerCase(), op = m[2], n = m[3] === undefined ? null : parseFloat(m[3])
    if (STAT_KEYS.indexOf(k) >= 0 && op && n !== null) return { type: 'stat', k: k, op: op, n: n }
    if (k === 'ate' && n !== null) return { type: 'ate', n: n }
    if (k === 'burn' && n !== null) return { type: 'burn', n: n }
    if (k === 'milk' && op === '-' && n !== null) return { type: 'milk', n: n }
    if (k === 'day') return { type: 'day', n: n || 1 }
  }
  return null
}
const TAG_MARK = '[Hidden tags'   // the opening words of our own reminder
function stripEcho(text) {   // if the AI repeats our reminder, take it out (with its nested [tags]) before anything is read from it
  let i = text.toLowerCase().indexOf(TAG_MARK.toLowerCase())
  while (i >= 0) {
    let depth = 0, j = i
    for (; j < text.length; j++) {
      if (text[j] === '[') depth++
      else if (text[j] === ']' && --depth === 0) break
    }
    if (j >= text.length) { j = text.indexOf('\n', i); if (j < 0) j = text.length - 1 }   // never closed: drop that line only
    text = text.slice(0, i) + text.slice(j + 1)
    i = text.toLowerCase().indexOf(TAG_MARK.toLowerCase())
  }
  return text
}
function parseTags(text) {
  text = stripEcho(text)
  const events = []
  const clean = text.replace(/\[[^\[\]\n]{1,80}\]/g, (tag) => {
    let who = '', t = tag
    const keys = npcKeys()
    for (let i = 0; i < keys.length; i++) {   // "[ate 300 Whitney]" or "[Whitney: ate 300]"
      const nm = esc(state.npcs[keys[i]].name || keys[i])
      const tail = new RegExp('\\s+' + nm + '\\s*\\]$', 'i'), head = new RegExp('^\\[\\s*' + nm + '\\s*[:,]?\\s+', 'i')
      if (tail.test(t)) { who = keys[i]; t = t.replace(tail, ']'); break }
      if (head.test(t)) { who = keys[i]; t = t.replace(head, '['); break }
    }
    const ev = parseOne(t)
    if (!ev) return tag   // not one of ours: leave it alone
    ev.who = who
    events.push(ev)
    return '\u0001'
  })
  return { clean: clean.replace(/ ?\u0001/g, ''), events: events }
}
function applyAll(events, useSkip) {   // sends each event to the right character; a new day passes for everyone
  const notes = [], groups = {}
  events.filter((e) => e.type !== 'day').forEach((e) => { const k = e.who || defKey(); (groups[k] = groups[k] || []).push(e) })
  Object.keys(groups).forEach((k) => {
    const s = sheetOf(k)
    if (!s) return
    applyEvents(s, groups[k], useSkip ? s.auto : null).forEach((n) => notes.push(labelOf(k) + n))
    state.bt_touched = (state.bt_touched || []).concat(state.bt_touched && state.bt_touched.indexOf(k) >= 0 ? [] : [k])
  })
  if (!(useSkip && state.bt.auto && state.bt.auto.day)) {
    events.filter((e) => e.type === 'day').forEach((e) => { notes.push(dayAll(Math.min(e.n, 30))) })
  }
  return notes
}
// "already counted this turn" guard: s.auto[type] is set by whatever counts first (typed text, a command, or the AI),
// and anything later of the same type for that character is dropped. Identical repeats inside one reply count once.
function applyEvents(s, events, skip) {
  if (skip) events = events.filter((e) => !skip[e.type])
  const seen = {}
  events = events.filter((e) => {
    if (e.type !== 'ate' && e.type !== 'burn') return true
    const id = e.type + e.n
    return seen[id] ? false : (seen[id] = true)
  })
  if (skip) events.forEach((e) => { if (e.type === 'ate' || e.type === 'burn' || e.type === 'train') s.auto[e.type] = true })
  const order = { stat: 0, curse: 1, lact: 2, ate: 3, burn: 4, train: 5, mana: 6, milk: 7, day: 8 }
  events.sort((a, b) => order[a.type] - order[b.type])
  const notes = []
  events.forEach((e) => {
    if (e.type === 'stat') notes.push(applyOp(s, e.k, e.op, e.n))
    else if (e.type === 'ate') { const n = Math.min(e.n, 5000); s.eaten = (s.eaten || 0) + n; notes.push('+' + fmt(n) + ' kcal') }
    else if (e.type === 'burn') { const n = Math.min(e.n, 3000); s.burned += n; notes.push('Burned ' + fmt(n) + ' kcal') }
    else if (e.type === 'train') { s.train[e.r] = Math.min(4, s.train[e.r] + e.n); notes.push('Trained ' + RWORD[e.r]) }
    else if (e.type === 'curse') notes.push(setCurse(s, e.op, e.name, e.r))
    else if (e.type === 'lact') { s.lact.on = e.on; notes.push('Lactation ' + (e.on ? 'on' : 'off')) }
    else if (e.type === 'mana') notes.push(doMana(s, e.sign, e.n, e.r))
    else if (e.type === 'milk') { const req = Math.min(e.n, 3000); const got = drainMilk(s, req); notes.push('Drained ' + Math.round(got) + ' ml') }
    else if (e.type === 'day') notes.push(advanceDays(s, e.n))
  })
  return notes
}

// ---------- spotting actions in what the player types (works without AI tags) ----------
// Text is lower-cased, stretched letters are squeezed ("sleeeep" -> "sleep") and matching forgives small typos.
const normText = (text) => text.toLowerCase()
  .replace(/\b(push|pull|sit|press)[- ]ups?\b/g, '$1up')
  .replace(/\bice[- ]cream\b/g, 'icecream')
  // multi-word foods become one word so the pieces ("hot", "dog", "soda") are not read on their own
  .replace(/\bhot[- ]dogs?\b/g, 'hotdog').replace(/\bcorn[- ]dogs?\b/g, 'corndog').replace(/\bpork[- ]chops?\b/g, 'porkchop')
  .replace(/\blamb[- ]chops?\b/g, 'lambchop').replace(/\bfried[- ]chicken\b/g, 'friedchicken')
  .replace(/\b(?:cotton[- ]candy|candy[- ]floss)\b/g, 'cottoncandy').replace(/\bfunnel[- ]cakes?\b/g, 'funnelcake')
  .replace(/\bcaramel[- ]apples?\b/g, 'caramelapple').replace(/\bs['’]?mores?\b/g, 'smores')
  .replace(/\bsweet[- ]tea\b/g, 'sweettea').replace(/\benergy[- ]drinks?\b/g, 'energydrink')
  // drinks with no calories must be joined before plain "soda" or "water" can be read
  .replace(/\b(?:diet|zero[- ]sugar|sugar[- ]free)[- ](?:soda|coke|cola|pepsi|lemonade)\b|\bcoke[- ]zero\b|\bzero[- ]sugar\b/g, 'dietsoda')
  .replace(/\bclub[- ]soda\b/g, 'clubsoda').replace(/\bsparkling[- ]water\b/g, 'sparklingwater')
  // things that look like food but are not
  .replace(/\bbaking[- ]soda\b/g, 'bakingsoda').replace(/\bpie[- ]charts?\b/g, 'piechart').replace(/\bcookie[- ]cutters?\b/g, 'cookiecutter')
  .replace(/\bcandy[- ](?:colou?red|striped|apple red)\b/g, 'candycolored')
  // drink sizes become one word each
  .replace(/\b(?:1|one)[- ]?(?:l|liter|litre)\b/g, 'oneliter').replace(/\b(?:2|two)[- ]?(?:l|liter|litre)s?\b/g, 'twoliter')
  .replace(/\b(?:64[- ]?oz|big[- ]gulp)\b/g, 'biggulp')
  .replace(/(.)\1{2,}/g, '$1$1')
  .replace(/[^a-z0-9'\- ]+/g, ' ')
const tokensOf = (text) => normText(text).split(/\s+/).filter(Boolean)
function editDist(a, b, subCost) {   // Damerau-Levenshtein: a swapped pair of letters counts as one typo
  const d = []
  for (let i = 0; i <= a.length; i++) { d.push([i]) }
  for (let j = 1; j <= b.length; j++) d[0][j] = j
  for (let i = 1; i <= a.length; i++) {
    for (let j = 1; j <= b.length; j++) {
      const c = a[i - 1] === b[j - 1] ? 0 : subCost
      d[i][j] = Math.min(d[i - 1][j] + 1, d[i][j - 1] + 1, d[i - 1][j - 1] + c)
      if (i > 1 && j > 1 && a[i - 1] === b[j - 2] && a[i - 2] === b[j - 1]) d[i][j] = Math.min(d[i][j], d[i - 2][j - 2] + 1)
    }
  }
  return d[a.length][b.length]
}
const NOT_THIS = { steak: ['stake', 'steal', 'steam', 'steel', 'stack', 'steep'], steaks: ['stakes', 'steals'], churro: ['church'], churros: ['churches'] }   // real words that must not be read as the food
function near(tok, word) {
  if (tok === word) return true
  if (NOT_THIS[word] && NOT_THIS[word].indexOf(tok) >= 0) return false
  if (!CFG.FUZZY) return false
  const L = word.length
  if (tok.length >= 3 && tok.length < L && tok.length >= L - 1 && word.startsWith(tok)) return true   // last letter missing ("cak")
  if (L === 3 && tok.length === 4 && tok.startsWith(word)) return true   // one extra letter on a 3-letter word ("eatt")
  const lim = L <= 3 ? 0 : L <= 8 ? 1 : 2
  if (lim === 0 || tok.length < 4 || Math.abs(tok.length - L) > lim) return false
  // short words must not change a letter ("lake" is not "cake", "sheep" is not "sleep")
  return editDist(tok, word, L <= 5 ? 2 : 1) <= lim
}
const findTok = (toks, words, from) => {
  for (let i = from || 0; i < toks.length; i++) { for (let k = 0; k < words.length; k++) { if (near(toks[i], words[k])) return i } }
  return -1
}

const FOODS = [   // [words, kcal per serving, kcal for the whole thing (optional)]
  [['cake', 'cakes', 'cheesecake', 'gateau'], 600, 12000],
  [['cupcake', 'cupcakes', 'muffin', 'muffins'], 350],
  [['shake', 'shakes', 'protein', 'smoothie', 'smoothies'], 130],
  [['pizza', 'pizzas'], 285, 2300],
  [['burger', 'burgers', 'cheeseburger', 'hamburger'], 550],
  [['sandwich', 'sandwiches', 'sub', 'wrap', 'burrito', 'taco', 'tacos'], 400],
  [['salad', 'salads'], 250],
  [['steak', 'steaks', 'chicken', 'pork', 'fish', 'meat', 'ribs', 'sausage', 'bacon', 'ham', 'turkey', 'lamb', 'ribeye', 'sirloin', 'porkchop', 'porkchops', 'lambchop', 'lambchops', 'brisket', 'roast', 'meatball', 'meatballs', 'kebab', 'kebabs', 'kabob', 'kebob', 'hotdog', 'hotdogs', 'wings', 'nuggets', 'friedchicken', 'bbq'], 450],
  [['pasta', 'spaghetti', 'noodles', 'noodle', 'lasagna', 'ramen', 'macaroni'], 450],
  [['rice', 'curry', 'sushi'], 300],
  [['soup', 'stew', 'porridge', 'oatmeal', 'cereal'], 250],
  [['fries', 'chips', 'crisps', 'nachos', 'popcorn', 'pretzel', 'pretzels', 'corndog', 'corndogs'], 400],
  [['bread', 'toast', 'bagel', 'roll', 'rolls'], 150],
  [['pancake', 'pancakes', 'waffle', 'waffles'], 150],
  [['cottoncandy', 'fudge', 'smores', 'caramelapple', 'churro', 'churros', 'funnelcake'], 300],
  [['egg', 'eggs', 'omelette', 'omelet'], 75],
  [['apple', 'apples', 'banana', 'bananas', 'fruit', 'orange', 'oranges', 'grapes', 'berries', 'strawberries', 'peach', 'pear'], 100],
  [['cookie', 'cookies', 'biscuit', 'biscuits', 'brownie', 'brownies'], 160],
  [['chocolate', 'candy', 'sweets', 'sweet', 'lollipop', 'gummies'], 250],
  [['icecream', 'gelato', 'sundae'], 300],
  [['donut', 'donuts', 'doughnut', 'doughnuts', 'pastry', 'pastries', 'croissant', 'pie', 'pies', 'tart'], 300],
  [['milk', 'juice', 'latte', 'cocoa', 'lemonade'], 150],
  [['soda', 'cola', 'coke', 'pepsi'], 140],
  [['beer', 'wine', 'cocktail', 'whiskey', 'vodka', 'ale'], 150],
  [['cheese', 'yogurt', 'yoghurt', 'butter'], 200],
  [['nuts', 'peanuts', 'almonds', 'granola', 'bar'], 200],
  [['sweettea', 'energydrink'], 150],
  [['dietsoda', 'clubsoda', 'sparklingwater'], 0],
  [['water', 'tea', 'coffee'], 0]
]
const MEALS = { breakfast: 450, brunch: 600, lunch: 600, dinner: 700, supper: 700, snack: 200, snacks: 300, meal: 500, dessert: 350, feast: 1500 }
const QTY = { a: 1, an: 1, one: 1, two: 2, three: 3, four: 4, five: 5, six: 6, seven: 7, eight: 8, nine: 9, ten: 10, couple: 2, few: 3, several: 3, both: 2 }
const STRONG_EAT = ['eat', 'eats', 'ate', 'eating', 'eaten', 'devour', 'devours', 'gulp', 'swallow', 'chew', 'munch', 'nibble', 'bite', 'drink', 'drinks', 'drank', 'sip', 'chug', 'consume', 'scarf', 'stuff', 'wolf', 'feast', 'dine', 'inhale', 'gorge', 'binge', 'feed', 'feeds', 'fed']
const WEAK_EAT = ['have', 'having', 'take', 'grab', 'try', 'taste', 'sample', 'finish', 'pour', 'order', 'get', 'grab', 'help', 'mix', 'make', 'cook', 'polish', 'share', 'split', 'serve', 'offer', 'give', 'hand', 'has', 'had']
// ---- lazy mode: a meal is a flat amount, scaled by the biggest/smallest size word near the food ----
const LAZY_KCAL = { meal: 700, snack: 300, sweet: 400 }
const LAZY_CLASS = {   // food group (first word of its FOODS row) -> class. Drinks and water are not listed: they keep their own kcal
  burger: 'meal', sandwich: 'meal', pizza: 'meal', salad: 'meal', steak: 'meal', pasta: 'meal', rice: 'meal', soup: 'meal',
  fries: 'snack', bread: 'snack', egg: 'snack', apple: 'snack', cheese: 'snack', nuts: 'snack',
  pancake: 'sweet', cottoncandy: 'sweet', cake: 'sweet', cupcake: 'sweet', cookie: 'sweet', chocolate: 'sweet', icecream: 'sweet', donut: 'sweet',
  breakfast: 'meal', brunch: 'meal', lunch: 'meal', dinner: 'meal', supper: 'meal', meal: 'meal', feast: 'meal', snack: 'snack', snacks: 'snack', dessert: 'sweet'
}
const SIZE = { massive: 1.5, huge: 1.5, giant: 1.5, double: 1.5, mountain: 1.5, small: 0.5, little: 0.5, tiny: 0.5, half: 0.5 }
function sizeNear(toks, i) {   // the largest size word in the 4 words before the food, or null
  let best = null
  for (let j = Math.max(0, i - 4); j < i; j++) { if (SIZE[toks[j]] && (best === null || SIZE[toks[j]] > best)) best = SIZE[toks[j]] }
  return best
}
function mealKcal(parts) {   // total kcal for the foods of one meal. Normal mode: the sum of the food table
  if (!lazyOn()) return parts.reduce((t, p) => t + p.kcal, 0)
  const by = { meal: [], snack: [], sweet: [] }
  let total = 0
  parts.forEach((p) => {
    if (by[p.cls]) by[p.cls].push(p)
    else if (p.drink && p.size) total += (p.kcal / p.qty) * Math.min(2, p.size * p.qty)   // a giant cup of soda
    else total += p.kcal
  })
  const main = by.meal.length ? 'meal' : by.sweet.length ? 'sweet' : ''   // snacks next to a meal or sweet are part of it
  ;['meal', 'sweet', 'snack'].forEach((c) => {
    let list = by[c]
    if (!list.length || (c === 'snack' && main)) return
    let sizes = list.map((p) => p.size).filter(Boolean)
    if (!sizes.length && c === main) sizes = by.snack.map((p) => p.size).filter((s) => s > 1)   // "a mountain of fries" makes the meal big
    const size = sizes.length ? Math.max.apply(null, sizes) : 1
    const qty = Math.max.apply(null, list.map((p) => p.qty))
    total += LAZY_KCAL[c] * Math.min(2, size * qty)
  })
  return total
}
const LABELS = { dietsoda: 'diet soda', clubsoda: 'club soda', sparklingwater: 'sparkling water', hotdog: 'hot dog', hotdogs: 'hot dogs', corndog: 'corn dog', corndogs: 'corn dogs', porkchop: 'pork chop', porkchops: 'pork chops', lambchop: 'lamb chop', lambchops: 'lamb chops', friedchicken: 'fried chicken', cottoncandy: 'cotton candy', funnelcake: 'funnel cake', caramelapple: 'caramel apple', smores: "s'mores", sweettea: 'sweet tea', energydrink: 'energy drink' }
const sipLine = (k, labels) => (nameOf(k) || 'You') + ' sipped ' + labels.map(withArticle).join(' and ') + ' (0 kcal, very virtuous)'
const withArticle = (l) => (/s$|water$|^fudge$|^bbq$/.test(l) ? l : 'a ' + l)
// ---- drinks: the container sets the amount (real kcal, also in lazy mode) ----
const DRINK_ROWS = ['milk', 'soda', 'sweettea']   // FOODS rows (first word) that use containers
const GAG = ['dietsoda', 'clubsoda', 'sparklingwater']   // zero-kcal drinks that get a light status line when named exactly (plain water counts 0 and says nothing)
const SIZE_DRINK = { oneliter: 420, twoliter: 840, biggulp: 800 }   // a named size can sit a few words away ("a 2-liter bottle of soda")
const CONTAINER = { can: 150, cans: 150, glass: 200, glasses: 200, cup: 200, cups: 200, bottle: 210, bottles: 210, jug: 420, jugs: 420 }   // must sit right next to the drink ("a can of soda")
function containerNear(toks, i) {   // kcal for the container around the drink word at i, or 0
  for (let j = Math.max(0, i - 4); j <= Math.min(toks.length - 1, i + 3); j++) { if (SIZE_DRINK[toks[j]]) return SIZE_DRINK[toks[j]] }
  const before = toks[i - 1] === 'of' ? toks[i - 2] : toks[i - 1]
  return CONTAINER[before] || CONTAINER[toks[i + 1]] || 0
}
function detectAte(text) { return detectAteInfo(text, false).kcal }
function detectAteInfo(text, force) {   // force: the caller already knows this sentence starts a meal, so no eating verb is needed
  const toks = tokensOf(text), foods = [], labels = [], parts = []
  const strong = findTok(toks, STRONG_EAT) >= 0, weak = findTok(toks, WEAK_EAT) >= 0
  if (!strong && !weak && !force) return { kcal: 0, foods: foods, label: '', parts: parts, gag: [] }
  let total = 0, found = false
  const qtyBefore = (i) => {   // nearest quantity word in the few words before the food
    for (let j = i - 1; j >= Math.max(0, i - 5); j--) {
      const w = toks[j]
      if (/^d+(?:.d+)?$/.test(w)) return w
      if (QTY[w] || w === 'half' || w === 'whole' || w === 'entire' || w === 'all') return w
    }
    return null
  }
  FOODS.forEach((f) => {
    const i = findTok(toks, f[0])
    if (i < 0) return
    found = true
    foods.push(f[0][0])
    const word = toks[i], lab = (SIZE[toks[i - 1]] ? toks[i - 1] + ' ' : '') + (LABELS[word] || word)
    labels.push(lab)
    const q = qtyBefore(i)
    const drink = DRINK_ROWS.indexOf(f[0][0]) >= 0, base = (drink && containerNear(toks, i)) || f[1]   // a can, glass or 2-liter sets the kcal of a soft drink
    let kcal = base
    if (q) {
      if (/^d/.test(q)) kcal = base * parseFloat(q)
      else if (QTY[q]) kcal = base * QTY[q]
      else if (q === 'half') kcal = f[2] ? f[2] / 2 : base * 0.5
      else kcal = f[2] ? f[2] : base * 4   // whole / entire / all
    }
    const num = q && (/^\d/.test(q) ? parseFloat(q) : QTY[q])
    parts.push({ food: f[0][0], word: word, kcal: kcal, label: lab, cls: LAZY_CLASS[f[0][0]], size: sizeNear(toks, i), qty: num || 1, drink: drink, gag: kcal === 0 && GAG.indexOf(word) >= 0 })   // gag: an exact zero-kcal drink, never a fuzzy match
  })
  Object.keys(MEALS).forEach((w) => {
    if (findTok(toks, [w]) >= 0 && !found) { found = true; foods.push(w); labels.push(w); parts.push({ food: w, word: w, kcal: MEALS[w], label: w, cls: LAZY_CLASS[w], size: null, qty: 1 }) }
  })
  if (!found) return { kcal: strong ? (lazyOn() ? LAZY_KCAL.meal : 400) : 0, foods: [], label: 'a meal', parts: parts, gag: [] }   // "I eat" with no food named counts as a plain meal; "I have" alone does not
  if (/\b(?:just a|a little|a tiny|a small) (?:taste|nibble|bite|sip)\b/.test(normText(text))) parts.forEach((p) => { p.size = 0.5 })   // "just a taste"
  return { kcal: Math.round(Math.min(mealKcal(parts), 5000)), foods: foods, label: labels.map(withArticle).join(' and '), parts: parts, gag: parts.filter((p) => p.gag).map((p) => p.label) }
}

const EX_LEGS = ['squat', 'squats', 'lunge', 'lunges', 'calf', 'legpress']
const EX_GLUTES = ['deadlift', 'deadlifts', 'thrust', 'thrusts', 'glute', 'glutes', 'bridges']
const EX_ARMS = ['curl', 'curls', 'bicep', 'biceps', 'tricep', 'triceps', 'pullup', 'pullups', 'dumbbell', 'dumbbells', 'kettlebell', 'kettlebells', 'barbell', 'barbells']
const EX_CHEST = ['pushup', 'pushups', 'bench', 'benchpress', 'fly', 'flies', 'flyes', 'pressup', 'pressups']
const EX_CORE = ['plank', 'planks', 'crunch', 'crunches', 'situp', 'situps', 'abs', 'core']
const EX_GENERIC = ['workout', 'workouts', 'exercise', 'exercises', 'exercising', 'gym', 'train', 'training', 'lift', 'lifting', 'lifts', 'weights', 'weight', 'reps', 'burpees', 'burpee', 'calisthenics']
const EX_CARDIO = ['jog', 'jogging', 'jogs', 'sprint', 'sprinting', 'treadmill', 'cardio', 'swim', 'swimming', 'aerobics']
const EX_ACTION = ['do', 'does', 'doing', 'did', 'perform', 'start', 'begin', 'hit', 'lift', 'lifting', 'use', 'using', 'grab', 'pick', 'curl', 'curls', 'press', 'pump', 'train', 'training', 'workout', 'exercise', 'exercising', 'work', 'swing', 'hoist', 'try', 'go', 'head', 'squat', 'squats', 'lunge', 'lunges', 'deadlift', 'deadlifts', 'plank', 'planks', 'jog', 'sprint', 'swim', 'crunches', 'burpees', 'pushups', 'situps', 'pullups']
function detectExercise(text) {
  const toks = tokensOf(text)
  if (findTok(toks, EX_ACTION) < 0) return null
  const regions = []
  const add = (rs) => rs.forEach((r) => { if (regions.indexOf(r) < 0) regions.push(r) })
  if (findTok(toks, EX_LEGS) >= 0) add(['legs'])
  if (findTok(toks, EX_GLUTES) >= 0) add(['glutes', 'legs'])
  if (findTok(toks, EX_ARMS) >= 0) add(['arms'])
  if (findTok(toks, EX_CHEST) >= 0) add(['chest', 'arms'])
  if (findTok(toks, EX_CORE) >= 0) add(['core'])
  const generic = findTok(toks, EX_GENERIC) >= 0
  const norm = normText(text)
  const cardio = findTok(toks, EX_CARDIO) >= 0 || /\brun(?:s|ning)? (?:laps|for|around|a mile|miles|km)\b|\bgo(?:es)? (?:for )?a run\b/.test(norm)
  if (generic && regions.length === 0) add(['legs', 'arms', 'chest'])
  if (regions.length === 0 && !cardio) return null
  const effort = findTok(toks, ['hard', 'heavy', 'intense', 'max', 'maximum', 'brutal', 'grueling', 'punishing', 'exhausting', 'intensely', 'vigorously']) >= 0 || /all[- ]out/.test(norm) ? 3
    : findTok(toks, ['light', 'easy', 'gentle', 'slow', 'warmup', 'casual', 'lightly', 'quick']) >= 0 ? 1 : 2
  return { regions: regions, effort: effort, burn: [150, 300, 450][effort - 1] }
}

const SLEEP_WORDS = ['sleep', 'sleeps', 'slept', 'asleep', 'bedtime', 'snooze', 'slumber']
function detectSleep(text) {
  const norm = normText(text)
  if (/\b(?:nap|naps|doze|dozes|can'?t sleep|cannot sleep|not sleep|don'?t sleep|unable to sleep|no sleep)\b/.test(norm)) return false
  const toks = tokensOf(text)
  if (findTok(toks, SLEEP_WORDS) >= 0) return true
  return /\b(?:go(?:es|ing)? to bed|turn(?:s|ing)? in\b|hit(?:s|ting)? the (?:hay|sack)|lie(?:s)? down (?:and|to) (?:sleep|rest)|call(?:s|ing)? it a night|lights out|rest (?:until|till|for the night|overnight)|(?:wait|stay|rest|wake|sleep)\w* (?:until|till|for) (?:the )?(?:morning|tomorrow|dawn|next day)|skip (?:to|ahead to) (?:the )?(?:morning|tomorrow|next day)|(?:the )?next (?:morning|day)|overnight|end (?:the|my|your|of the) day)\b/.test(norm)
}
function autoDetectAll(text) {
  const res = { notes: [], touched: [] }
  if (!CFG.AUTO) return res
  const names = whoIn(text)   // tracked names, and '' when the text says your own name (Rue)
  let keys = state.bt_hideYou ? [] : ['']   // with your sheet hidden, what you do yourself is not tracked
  const sharing = SHARE_RE.test(text), we = /\b(?:we|us|our)\b/i.test(text)
  if (names.length) {   // "Whitney eats cake" goes to Whitney; "I share a cake with Whitney" goes to both
    const both = sharing || we || /\bboth\b/i.test(text) || names.some((k) => {
      const nm = esc(nameOf(k) || k)
      return new RegExp('\\bwith\\s+' + nm + '\\b|\\b' + nm + '\\s+and\\s+(?:i|me|you)\\b|\\b(?:i|me|you)\\s+and\\s+' + nm + '\\b', 'i').test(text)
    })
    keys = both && !state.bt_hideYou && names.indexOf('') < 0 ? [''].concat(names) : names
  } else if (we) {   // "we share fries": everyone tracked
    keys = (state.bt_hideYou ? [] : ['']).concat(npcKeys())
  }
  const split = lazyOn() && keys.length > 1 && sharing && !/\beach\b/i.test(text) ? keys.length : 1   // lazy mode: sharing one meal means each gets a share, not the whole thing
  const ev = []
  const ate = detectAteInfo(text, false), kcal = ate.kcal, ex = detectExercise(text)
  keys.forEach((k) => {
    const s = sheetOf(k)
    if (!s) return
    if (kcal > 0) {
      const mine = Math.round(kcal / split)
      ev.push({ type: 'ate', n: mine, who: k }); s.auto.ate = true; s.lastAuto = { kcal: Math.min(mine, 5000), label: (split > 1 ? 'a share of ' : '') + ate.label, at: turnNo() * 10 }
    }
    if (ex) {
      ev.push({ type: 'burn', n: ex.burn, who: k }); s.auto.burn = true
      ex.regions.forEach((r) => { ev.push({ type: 'train', r: r, n: ex.effort, who: k }); s.auto.train = true })
    }
  })
  if (kcal > 0 || ex) res.touched = keys.slice()
  const nowCount = typeof info !== 'undefined' && info && typeof info.actionCount === 'number' ? info.actionCount : 0
  if (detectSleep(text) && (!state.bt.lastDayAt || !nowCount || nowCount - state.bt.lastDayAt >= 4)) {
    ev.push({ type: 'day', n: 1 }); state.bt.auto.day = true; state.bt.lastDayAt = nowCount
    res.touched = ['']
  }
  state.bt_touched = []
  res.notes = applyAll(ev, false)
  if (ate.gag.length) {   // a zero-kcal drink: nothing counted, just a light line
    keys.forEach((k) => { if (sheetOf(k)) res.notes.push(sipLine(k, ate.gag)) })
    if (!res.touched.length) res.touched = keys.slice()
  }
  if (res.notes.length) res.touched = res.touched.length ? res.touched : state.bt_touched
  return res
}

// ---------- spotting meals in the AI's reply (Output tab) ----------
// Only the start of a meal counts: served, ordered, grabbed, dug into, "eats a ...". Wording that continues or only
// talks about a meal (another bite, chews, finishes, looks at, wants) does not. A meal goes to a character only when
// the sentence names them (or says "you" and the player has a sheet), otherwise nothing is counted. All sentences
// about one meal in a reply are merged and counted once, and the same character + food word is not counted again
// for NARRATE_COOLDOWN actions, so order, arrival, bites and "devours the rest" over several replies are one meal.
const NARRATE_COOLDOWN = 3
const START_RE = /\b(?:arrives?|arrived|orders?|ordered|ordering|grabs?|grabbed|digs? into|dug into|tucks? into|starts? (?:on|eating)|begins? (?:to eat|eating)|brings?|serves?|served|sets? down|slides? (?:over|across)|eats?|ate|shares?|split|splits|drinks?|sips?|chugs?|guzzles?|cracks? open|helps? (?:herself|himself|themselves) to|picks? up)\b/i
const CONT_RE = /\b(?:another (?:bite|nibble|sip|taste|piece|forkful|spoonful)|takes? (?:a|one|the) (?:bite|nibble|sip|taste)|bites? into|chews?|chewing|savou?rs?|savou?ring|finish(?:es|ed)?|the rest|last (?:bite|piece|crumb)|licks?|swallows?|polish(?:es|ed)? off|wipes?|leftovers?|looks? (?:at|down)|stares?|eyes|smells?|watch(?:es|ed)|admires?|considers?|wants?|wonders?)\b/i

const DISHES = ['burger', 'burgers', 'cheeseburger', 'hamburger', 'sandwich', 'sandwiches', 'pizza', 'pizzas', 'salad', 'pasta', 'cake', 'steak', 'steaks', 'ribeye', 'sirloin', 'ribs', 'porkchop', 'porkchops', 'lambchop', 'lambchops', 'brisket', 'roast', 'meatball', 'meatballs', 'kebab', 'kebabs', 'kabob', 'kebob', 'hotdog', 'hotdogs', 'sausage', 'wings', 'nuggets', 'friedchicken', 'bbq', 'burrito', 'taco', 'tacos']   // when one of these words is in the sentence, its ingredients are not separate foods
const INGREDIENTS = ['meat', 'cheese', 'bacon', 'ham', 'egg', 'eggs', 'butter', 'bread', 'chicken', 'pork', 'lamb', 'turkey']
function narratedEaters(sent) {   // keys of the characters this sentence is about; [] means do not guess
  const names = whoIn(sent)   // tracked names, and '' when the sentence says the player's name (Rue)
  const sharing = SHARE_RE.test(sent)
  if (names.length > 1) return sharing || /\b(?:both|together|and)\b/i.test(sent) ? names : []
  if (names.length === 1) {   // "Whitney and I share a sundae": you are in it too
    if (names[0] !== '' && sharing && !state.bt_hideYou && /\b(?:i|me|we|us)\b|\byou\s+and\b|\band\s+you\b|\bwith\s+you\b/i.test(sent)) return ['', names[0]]
    return names
  }
  if (/\b(?:we|us)\b/i.test(sent)) return (state.bt_hideYou ? [] : ['']).concat(npcKeys())   // "we share fries": everyone tracked
  if (/\byou(?:r|rs)?\b/i.test(sent)) {
    const you = CFG.YOU_NAME && state.npcs[CFG.YOU_NAME.toLowerCase()] ? CFG.YOU_NAME.toLowerCase() : ''
    if (you) return [you]
    if (!state.bt_hideYou) return ['']
  }
  return []
}
function narratedMeals(text, count) {   // returns [{ key, kcal, parts, label }]
  const found = {}
  const sentences = text.replace(/\[[^\]]*\]/g, ' ').replace(/\.{2,}|…/g, ' ').split(/(?<=[.!?])\s+|[;\n]+|\s*[—–,]\s*and\s+(?=[A-Z])/)   // also "..., and Whitney nudges ...": a new clause with its own subject
  sentences.forEach((sent) => {
    const at = sent.search(CONT_RE)
    const head = at >= 0 ? sent.slice(0, at) : sent   // what happens before "takes another bite" still counts
    if (!START_RE.test(head)) return
    const all = detectAteInfo(head, true).parts
    let parts = all.filter((p) => p.kcal > 0)   // water, tea and typo matches like "waiter" do not count
    if (parts.some((p) => DISHES.indexOf(p.word) >= 0)) parts = parts.filter((p) => INGREDIENTS.indexOf(p.word) < 0)   // "burger ... slabs of meat" is one dish
    const gags = all.filter((p) => p.gag)   // exact zero-kcal drinks: not counted, but they get a light status line
    if (!parts.length && !gags.length) return
    const who = narratedEaters(sent)
    const share = lazyOn() && who.length > 1 && SHARE_RE.test(sent) && !/\beach\b/i.test(sent) ? who.length : 1   // lazy mode: a shared meal is split between them
    who.forEach((k) => {
      found[k] = found[k] || {}
      found[k].__share = Math.max(found[k].__share || 1, share)
      gags.forEach((p) => { (found[k].__gag = found[k].__gag || {})[p.food] = p })
      parts.forEach((p) => {
        const old = found[k][p.food]   // the same food in another sentence keeps the bigger size word and quantity
        found[k][p.food] = old ? Object.assign({}, p, { size: Math.max(old.size || 0, p.size || 0) || null, qty: Math.max(old.qty, p.qty), label: old.label.length >= p.label.length ? old.label : p.label }) : p
      })
    })
  })
  const out = []
  Object.keys(found).forEach((k) => {
    const s = sheetOf(k)
    if (!s || s.auto.ate) return   // already counted this turn by typed text, a command or an AI tag
    const cool = s.cool || {}
    const gagMap = found[k].__gag || {}
    delete found[k].__gag
    const share = found[k].__share || 1
    delete found[k].__share
    const cold = (f) => cool[f] === undefined || Math.abs(count - cool[f]) > NARRATE_COOLDOWN
    const sips = Object.keys(gagMap).filter(cold).map((f) => gagMap[f])
    if (sips.length) out.push({ key: k, kcal: 0, parts: sips, label: sips.map((p) => withArticle(p.label)).join(' and '), gag: true })
    const fresh = Object.keys(found[k]).filter(cold).map((f) => found[k][f])
    if (!fresh.length) return
    const kcal = mealKcal(fresh) / share   // one amount for the whole meal (lazy mode: the double burger with a mountain of fries is one 700 x 1.5)
    out.push({ key: k, kcal: Math.round(Math.min(kcal, 5000)), parts: fresh, label: fresh.map((p) => withArticle(p.label)).join(' and ') })
  })
  return out
}
function countNarrated(text) {   // adds the meals found in the AI's reply and returns the status notes
  const count = typeof info !== 'undefined' && info && typeof info.actionCount === 'number' && info.actionCount > 0 ? info.actionCount : (typeof history !== 'undefined' && history ? history.length : 0)
  const notes = []
  narratedMeals(text, count).forEach((o) => {
    const s = sheetOf(o.key)
    if (o.gag) {   // a zero-kcal drink: nothing to count, just the light line (and the cooldown, so it is not repeated)
      s.cool = s.cool || {}
      o.parts.forEach((p) => { s.cool[p.food] = count })
      state.bt_touched = (state.bt_touched || []).concat([o.key])
      notes.push(sipLine(o.key, o.parts.map((p) => p.label)))
      return
    }
    s.eaten = (s.eaten || 0) + o.kcal
    s.auto.ate = true
    s.cool = s.cool || {}
    o.parts.forEach((p) => { s.cool[p.food] = count })
    s.lastAuto = { kcal: o.kcal, label: o.label, at: turnNo() * 10 + 1 }   // at orders meals: typed text (Input) before the AI's reply (Output) of the same turn
    state.bt_touched = (state.bt_touched || []).concat([o.key])
    notes.push('Counted: ' + (nameOf(o.key) || 'You') + ' ate ' + o.label + ' (~' + fmt(o.kcal) + ' kcal). Type :undo meal to remove.')
  })
  if (notes.length) state.bt_flag = true
  return notes
}

// ---------- commands typed by the player ----------
const CMD_RE = [
  ['sheetadd', /:sheet[ \t]+add[ \t]+([A-Za-z][\w\-]*)((?:[ \t]+\w+=[\w.\-]+)*)/i],
  ['sheetremove', /:sheet[ \t]+remove[ \t]+([A-Za-z][\w\-]*)/i],
  ['sheetlist', /:sheet[ \t]+list\b/i],
  ['sheetyou', /:sheet[ \t]+you[ \t]+(on|off)/i],
  ['set', /:set[ \t]+(\w+)[ \t]+(-?\d+(?:\.\d+)?)/i],
  ['undomeal', /:undo[ \t]+meal\b/i],
  ['eat',/:eat[ \t]+(\d+)/i],
  ['burn', /:burn[ \t]+(\d+)/i],
  ['train', /:train[ \t]+(chest|arms|core|glutes|legs)(?:[ \t]+([1-3]))?/i],
  ['day', /:day(?:[ \t]+(\d+))?\b/i],
  ['gland', /:gland[ \t]+([+-]?\d+)/i],
  ['potential', /:potential[ \t]+([+-]?\d+)/i],
  ['lactate', /:lactate[ \t]+(on|off)/i],
  ['milk', /:milk[ \t]+(\d+)/i],
  ['mana', /:mana[ \t]+([+-])(\d+)(?:[ \t]+(chest|arms|core|glutes|legs))?/i],
  ['curse', /:curse[ \t]+(add|remove)[ \t]+(hunger|leech|forced|bias)(?:[ \t]+(chest|arms|core|glutes|legs))?/i],
  ['support', /:support[ \t]+(on|off)/i],
  ['look', /:look[ \t]+(curvy|athletic|soft|off)/i],
  ['pace', /:pace[ \t]+(\d+(?:\.\d+)?)/i],
  ['reset', /:reset[ \t]+confirm/i],
  ['inspect', new RegExp(':(?:inspect|scan)(?:[ \\t]+' + PART_RE + ')?\\b', 'i')],
  ['body', /:body\b/i],
  ['help', /:help\b/i],
  ['probe', /:probe\b/i]   // only when CFG.PROBE is on (the custom build); otherwise the text is left alone
]
function parseCommand(text) {
  for (let i = 0; i < CMD_RE.length; i++) {
    if (CMD_RE[i][0] === 'probe' && !CFG.PROBE) continue
    const m = text.match(CMD_RE[i][1])
    if (m) return { name: CMD_RE[i][0], m: m, who: CMD_RE[i][0].indexOf('sheet') === 0 ? [] : whoIn(text) }
  }
  return null
}
const HELP = 'Other characters: :sheet add Name [weight=68 bodyfat=30 ...], :sheet remove Name, :sheet list, :sheet you off|on. Put a name on any command to target them, like :eat 600 Name. Commands: :set stat value, :eat kcal, :undo meal [Name], :burn kcal, :train area [1-3], :day [n], :gland +/-cc, :potential +/-cc, :lactate on/off, :milk ml, :mana +/-n [area], :curse add/remove hunger|leech|forced|bias [area], :support on/off, :look curvy/athletic/soft/off, :pace n, :inspect [chest|arms|core|glutes|legs|body], :scan, :body, :help. Stats: ' + STAT_KEYS.join(' ')
// key=value options of a sheet, shared by ":sheet add Name ..." and the Player setup card.
// Lenient (the :sheet add way): unknown or bad parts are ignored. strict: bad parts are collected in bad[] so they can be reported.
// Blank values ("height=") always mean "keep the default".
function parseSheetOpts(str, strict) {
  const st = {}, o = {}, bad = []
  String(str || '').trim().split(/\s+/).filter(Boolean).forEach((p) => {
    const i = p.indexOf('=')
    if (i < 0) { if (strict) bad.push(p); return }
    const key = p.slice(0, i).toLowerCase(), val = p.slice(i + 1)
    if (val === '') return
    if (key === 'muscle' || key === 'activity') {   // starting muscle multiplier (0.5-1.5) and activity factor (1.0-2.0)
      const lim = key === 'muscle' ? [0.5, 1.5] : [1.0, 2.0], n = parseFloat(val)
      if (/^\d+(?:\.\d+)?$/.test(val) && n >= lim[0] && n <= lim[1]) o[key] = n
      else if (strict) bad.push(p)
      return
    }
    if (key === 'pattern') { if (PATTERNS[val]) o.pattern = val; else if (strict) bad.push(p) }
    else if (key === 'look') { if (LOOKS.indexOf(val) >= 0) o.look = val; else if (strict) bad.push(p) }
    else if (key === 'name' && strict) { if (/^[A-Za-z][\w-]*$/.test(val)) o.name = val; else bad.push(p) }
    else if (CFG.START[key] !== undefined) {
      if (!strict) { if (!isNaN(parseFloat(val))) st[key] = parseFloat(val); return }
      const lim = LIMITS[key] || [0, 600], n = parseFloat(val)
      if (/^\d+(?:\.\d+)?$/.test(val) && n >= lim[0] && n <= lim[1]) st[key] = n
      else bad.push(p)
    } else if (strict) bad.push(p)
  })
  return { st: st, o: o, bad: bad }
}
function runCommand(cmd) {
  const key = (cmd.who && cmd.who[0]) || (cmd.name.indexOf('sheet') === 0 ? '' : defKey())
  const s = sheetOf(key), m = cmd.m
  let line = '\n> You take stock of your body.\n', note = ''
  state.bt_touched = [key]
  switch (cmd.name) {
    case 'set': {
      const k = m[1].toLowerCase()
      note = STAT_KEYS.indexOf(k) >= 0 ? applyOp(s, k, '=', parseFloat(m[2])) : 'Unknown stat "' + k + '"'
      break
    }
    case 'eat': {
      const n = Math.min(parseInt(m[1], 10), 5000)
      s.eaten = (s.eaten || 0) + n
      note = 'Ate ' + fmt(n) + ' kcal'
      line = '\n> You eat a meal.\n'
      break
    }
    case 'undomeal': {   // takes back the last meal the tracker counted by itself (once per meal)
      let keys
      if (cmd.who && cmd.who.length) keys = cmd.who   // ":undo meal Whitney" / ":undo meal Rue": only that person
      else {   // no name: the most recent auto-counted meal (a shared meal is taken back from everyone in it)
        const have = [''].concat(npcKeys()).filter((k) => sheetOf(k) && sheetOf(k).lastAuto)
        const top = Math.max.apply(null, have.map((k) => sheetOf(k).lastAuto.at || 0))
        keys = have.filter((k) => (sheetOf(k).lastAuto.at || 0) === top)
      }
      const done = []
      keys.forEach((k) => {
        const x = sheetOf(k)
        if (!x || !x.lastAuto) return
        x.eaten = Math.max(0, (x.eaten || 0) - x.lastAuto.kcal)
        done.push((nameOf(k) || 'You') + ': ' + x.lastAuto.label + ' (' + fmt(x.lastAuto.kcal) + ' kcal)')
        x.lastAuto = null
      })
      note = done.length ? 'Removed ' + done.join(' | ') : 'No auto-counted meal to remove'
      state.bt_touched = keys.length ? keys : [key]
      line ='\n> You think back over what you ate.\n'
      break
    }
    case 'burn': {
      const n = Math.min(parseInt(m[1], 10), 3000)
      s.burned += n
      note = 'Burned ' + fmt(n) + ' extra kcal'
      line = '\n> You work out.\n'
      break
    }
    case 'train': {
      const r = m[1].toLowerCase(), e = m[2] ? parseInt(m[2], 10) : 2
      s.train[r] = Math.min(4, s.train[r] + e)
      note = 'Trained ' + RWORD[r] + ' (effort ' + e + ')'
      line = '\n> You train your ' + RWORD[r] + '.\n'
      break
    }
    case 'day': {
      const n = m[1] ? parseInt(m[1], 10) : 1
      note = dayAll(n)
      state.bt_touched = [''].concat(npcKeys())
      line = n > 1 ? '\n> You rest while ' + clampN(n, 1, 30) + ' days pass.\n' : '\n> You go to sleep and wake up the next morning.\n'
      break
    }
    case 'gland': {
      const n = parseInt(m[1], 10)
      note = applyOp(s, 'gland', '+', n)
      break
    }
    case 'potential': note = applyOp(s, 'potential', '+', parseInt(m[1], 10)); break
    case 'lactate': s.lact.on = m[1].toLowerCase() === 'on'; note = 'Lactation ' + (s.lact.on ? 'on' : 'off'); break
    case 'milk': {
      const req = Math.min(parseInt(m[1], 10), 3000), got = drainMilk(s, req)
      note = 'Drained ' + Math.round(got) + ' ml'
      line = '\n> You drain some milk.\n'
      break
    }
    case 'mana': {
      note = doMana(s, m[1], parseFloat(m[2]), m[3] ? m[3].toLowerCase() : 'all')
      line = m[1] === '+' ? '\n> You channel mana into your body.\n' : '\n> You spend some mana.\n'
      break
    }
    case 'curse': {
      note = setCurse(s, m[1].toLowerCase(), m[2].toLowerCase(), m[3] ? m[3].toLowerCase() : '')
      line = m[1].toLowerCase() === 'add' ? '\n> You feel a curse take hold.\n' : '\n> You feel a curse lift.\n'
      break
    }
    case 'inspect': {
      const part = m[1] ? PARTS[m[1].toLowerCase()] : 'all'   // :scan on its own inspects everything
      state.bt_inspect = part
      state.bt_inspectWho = key
      note = 'Inspecting ' + part
      line = part === 'all' ? '\n> You step into the scanner.\n' : '\n> You inspect your ' + (part === 'core' ? 'midsection' : part) + ' closely.\n'
      break
    }
    case 'support': s.support = m[1].toLowerCase() === 'on'; note = 'Support ' + (s.support ? 'on' : 'off'); break
    case 'look': s.look = m[1].toLowerCase(); note = 'Look: ' + s.look; break
    case 'pace': s.pace = clampN(parseFloat(m[1]), 0.5, 10); s.paceSet = true; note = 'Growth pace ' + s.pace; break
    case 'reset': state.bt = newPlayer(); note = 'Tracker reset'; break
    case 'sheetadd': {
      const name = m[1], k = name.toLowerCase()
      const parsed = parseSheetOpts(m[2])
      const st = parsed.st, o = parsed.o
      o.name = name
      state.npcs[k] = newBT(st, o)
      note = 'Added a sheet for ' + name + (Object.keys(st).length ? ' (' + Object.keys(st).map((x) => x + ' ' + st[x]).join(', ') + ')' : '')
      line = '\n> You take a moment to think about ' + name + '.\n'
      state.bt_touched = [k]
      break
    }
    case 'sheetremove': {
      const k = m[1].toLowerCase()
      if (state.npcs[k]) { note = 'Removed the sheet for ' + state.npcs[k].name; delete state.npcs[k] } else note = 'No sheet for ' + m[1]
      state.bt_touched = ['']
      break
    }
    case 'sheetlist': note = 'Sheets: You' + npcKeys().map((k) => ', ' + state.npcs[k].name).join('') + (state.bt_hideYou ? ' (your own sheet is hidden)' : ''); state.bt_touched = ['']; break
    case 'sheetyou': state.bt_hideYou = m[1].toLowerCase() === 'off'; note = 'Your own sheet is ' + (state.bt_hideYou ? 'hidden' : 'shown'); state.bt_touched = ['']; break
    case 'probe': {   // changes no sheet: only writes the "probe" story card
      note = probeCard()
      line = '\n> You take a long look around.\n'
      break
    }
    case 'help': state.bt_help = true; break
    default: break   // body
  }
  const HANDLED = { eat: 'ate', burn: 'burn', train: 'train', day: 'day', milk: 'milk', mana: 'mana', lactate: 'lact', curse: 'curse' }
  if (HANDLED[cmd.name] && s && s.auto) s.auto[HANDLED[cmd.name]] = true   // so the AI's own tag for it is not counted twice
  return { line: line, note: (key && note && cmd.name.indexOf('sheet') !== 0 && cmd.name !== 'undomeal' ? labelOf(key) : '') + note, matched: m[0] }
}

// ---------- text for the AI, the card and the status line ----------
function aiLine(s) {
  const notes = []
  REGIONS.forEach((r) => {
    const mr = s.mus[r] / s.mus0[r], fr = s.fat[r] / s.fat0[r], w = RWORD[r]
    if (mr >= 1.12) notes.push([mr - 1, 'muscular ' + w])
    else if (mr >= 1.04) notes.push([mr - 1, 'toned ' + w])
    if (fr >= 1.25) notes.push([fr - 1, 'softer ' + w])
    else if (fr >= 1.08) notes.push([fr - 1, 'slightly fuller ' + w])
    else if (fr <= 0.75) notes.push([1 - fr, 'leaner ' + w])
    else if (fr <= 0.92) notes.push([1 - fr, 'slightly slimmer ' + w])
  })
  notes.sort((a, b) => b[0] - a[0])
  const txt = notes.slice(0, 4).map((n) => n[1]).join(', ')
  return txt ? txt.charAt(0).toUpperCase() + txt.slice(1) : 'No notable changes yet'
}

// ---------- shape and size adjectives ----------
// Each list is [upper limit, word]: the first limit the value falls under gives the word. Edit the words freely.
// 'average' entries are left out of the description, so it only mentions what stands out.
const LOOK_WORDS = {
  height: [[150, 'petite'], [158, 'short'], [168, 'average height'], [177, 'tall'], [184, 'very tall'], [999, 'towering']],   // cm
  build: [[14, 'very lean'], [19, 'lean'], [24, 'slim'], [30, 'medium'], [35, 'soft'], [41, 'plush'], [48, 'heavyset'], [999, 'very heavyset']],   // body fat %
  bust: [[2, 'flat'], [3, 'small'], [4, 'modest'], [5, 'full'], [6, 'large'], [8, 'very large'], [10, 'huge'], [99, 'enormous']],   // cup index (A = 2, B = 3, C = 4, D = 5)
  waist: [[0.66, 'very narrow'], [0.72, 'narrow'], [0.78, 'defined'], [0.85, 'soft'], [0.93, 'thick'], [9, 'wide']],   // waist / hips
  hips: [[0.50, 'narrow'], [0.56, 'slim'], [0.62, 'average'], [0.68, 'wide'], [0.75, 'very wide'], [9, 'broad']],   // hips / height
  thigh: [[0.27, 'slender'], [0.31, 'slim'], [0.36, 'average'], [0.41, 'thick'], [0.47, 'very thick'], [9, 'massive']],   // thigh / height
  arm: [[0.135, 'slender'], [0.155, 'slim'], [0.18, 'average'], [0.21, 'sturdy'], [9, 'thick']]   // upper arm / height
}
const tier = (table, v) => {
  for (let i = 0; i < table.length; i++) { if (v < table[i][0]) return table[i][1] }
  return table[table.length - 1][1]
}
function shapeName(m) {
  const whr = m.waist / m.hips, diff = (m.bust - m.hips) / m.hips
  if (whr > 0.85) return 'apple-shaped'
  if (whr <= 0.76 && Math.abs(diff) <= 0.08) return 'hourglass'
  if (diff < -0.08) return 'pear-shaped'
  if (diff > 0.08) return 'inverted-triangle'
  return 'straight'
}
function describeLook(s, m) {
  const H = m.height, bf = m.bodyfat
  const wr = (s.mus.legs + s.mus.glutes + 1.3 * s.mus.arms + 1.2 * s.mus.chest + 0.9 * s.mus.core) / (23.01 * Math.pow(H / s.start.height, 2) * (s.start.weight / 60))
  const prefix = wr >= 1.25 ? 'muscular' : wr >= 1.1 ? 'athletic' : wr >= 1.04 ? 'toned' : ''
  const build = (prefix ? prefix + ', ' : '') + tier(LOOK_WORDS.build, bf)
  const cupIdx = clampN(Math.round((m.bust - m.underbust - 7.5) / 2.5), 0, CUPS.length - 1)
  const extras = []
  const hw = tier(LOOK_WORDS.hips, m.hips / H), tw = tier(LOOK_WORDS.thigh, m.thigh / H), aw = tier(LOOK_WORDS.arm, m.arm / H)
  if (hw !== 'average') extras.push(hw + ' hips')
  if (tw !== 'average') extras.push(tw + ' thighs')
  if (aw !== 'average') extras.push(aw + ' arms')
  const lr = s.mus.legs / s.mus0.legs, ar = s.mus.arms / s.mus0.arms
  if (lr >= 1.12) extras.push('muscular legs'); else if (lr >= 1.04) extras.push('toned legs')
  if (ar >= 1.12) extras.push('muscular arms'); else if (ar >= 1.06) extras.push('toned arms')
  const gm = s.mus.glutes / s.mus0.glutes, gf = s.fat.glutes / s.fat0.glutes
  if (gf >= 1.2) extras.push('full glutes'); else if (gm >= 1.1) extras.push('firm, rounded glutes')
  const cf = s.fat.core / s.fat0.core, cm = s.mus.core / s.mus0.core
  if (cf >= 1.25) extras.push('soft belly'); else if (cf <= 0.85 && bf < 22) extras.push('flat stomach')
  if (cm >= 1.12 && bf < 20) extras.push('defined abs')
  return 'Look: ' + tier(LOOK_WORDS.height, H) + ', ' + build + ' ' + shapeName(m) + ' figure; ' + tier(LOOK_WORDS.bust, cupIdx) + ' bust; ' +
    tier(LOOK_WORDS.waist, m.waist / m.hips) + ' waist' + (extras.length ? '; ' + extras.join(', ') : '')
}

// ---------- inspecting one body part ----------
function inspectPart(s, part) {
  const m = measures(s), a = abilities(s, m), H = m.height
  const dl = (v, base, dec) => (Math.abs(v - base) < 0.005 ? '' : ' (' + sgn(v - base) + (dec === 2 ? r2(v - base) : r1(v - base)) + ')')
  const musFat = (r) => 'muscle ' + r2(s.mus[r]) + ' kg' + dl(s.mus[r], s.mus0[r], 2) + ', fat ' + r2(s.fat[r]) + ' kg' + dl(s.fat[r], s.fat0[r], 2)
  const mana = (r) => 'Mana ' + Math.round(s.mana[r]) + ' of ' + Math.round(manaCap(s, r)) + '.'
  if (part === 'chest') {
    const c = chestCalc(s), V = c.V
    const cupIdx = clampN(Math.round((m.bust - m.underbust - 7.5) / 2.5), 0, CUPS.length - 1)
    let t = 'Chest inspection: ' + tier(LOOK_WORDS.bust, cupIdx) + ' bust, bra ' + cup(m) + ' (bust ' + r1(m.bust) + ' cm over underbust ' + r1(m.underbust) + ' cm). Each breast about ' + Math.round(V.total) + ' cc: glandular ' +
      Math.round(V.gland) + ' cc (' + Math.round(c.g * 100) + '% of tissue), fat ' + Math.round(V.fat) + ' cc (' + Math.round(V.fat / V.tissue * 100) + '%)' + (V.milk > 1 ? ', milk ' + Math.round(V.milk) + ' cc' : '') +
      '. ' + firmWord(c.firm).charAt(0).toUpperCase() + firmWord(c.firm).slice(1) + ' (firmness ' + Math.round(c.firm) + ' of 100), ' + sagWord(s.sag) + ' (sag ' + r1(s.sag) + ' of 3). Chest ' + musFat('chest') + '. '
    if (lactActive(s) || s.lact.stored > 1) t += 'Milk ' + Math.round(s.lact.stored) + ' of ' + Math.round(milkCap(s)) + ' ml stored, supply ' + Math.round(s.lact.sup * 100) + '%. '
    return t + mana('chest') + ' Glandular tissue can grow to about ' + Math.round(glandCeil(s)) + ' cc.'
  }
  if (part === 'arms') return 'Arm inspection: ' + tier(LOOK_WORDS.arm, m.arm / H) + ' arms, upper arm ' + r1(m.arm) + ' cm. Arms ' + musFat('arms') + '. ' + mana('arms') + ' Strength ' + a.str.score + '.'
  if (part === 'core') return 'Core inspection: ' + tier(LOOK_WORDS.waist, m.waist / m.hips) + ' waist, ' + r1(m.waist) + ' cm (waist to hip ' + r2(m.waist / m.hips) + '). Core ' + musFat('core') + '. ' + mana('core') + (s.fat.core / s.fat0.core >= 1.25 ? ' The belly is soft and rounded.' : s.fat.core / s.fat0.core <= 0.85 ? ' The stomach is flat.' : '')
  if (part === 'glutes') return 'Hip and glute inspection: ' + tier(LOOK_WORDS.hips, m.hips / H) + ' hips, ' + r1(m.hips) + ' cm. Glutes ' + musFat('glutes') + '. ' + mana('glutes') + (s.fat.glutes / s.fat0.glutes >= 1.2 ? ' Noticeably full.' : s.mus.glutes / s.mus0.glutes >= 1.1 ? ' Firm and rounded.' : '')
  if (part === 'legs') return 'Leg inspection: ' + tier(LOOK_WORDS.thigh, m.thigh / H) + ' thighs, ' + r1(m.thigh) + ' cm around. Legs ' + musFat('legs') + '. ' + mana('legs') + ' Dexterity ' + a.dex.score + '.'
  return 'Full inspection: ' + describeLook(s, m).replace(/^Look: /, '') + '. ' + r1(m.height) + ' cm, ' + r1(m.weight) + ' kg, body fat ' + r1(m.bodyfat) + '%, muscle ' + r1(sum(s.mus)) + ' kg, bra ' + cup(m) + '. Stats: ' + statLine(a) + '.'
}
function detectInspect(text) {
  const toks = tokensOf(text)
  const vi = findTok(toks, ['inspect', 'examine', 'scan', 'check', 'study', 'measure', 'look', 'see', 'view'])
  if (vi >= 0) {
    const strongVerb = findTok(toks, ['inspect', 'examine', 'scan', 'check', 'study', 'measure']) >= 0
    const words = Object.keys(PARTS).filter((w) => strongVerb || (w !== 'all' && w !== 'body'))   // "look at" only counts for a specific part
    for (let i = vi + 1; i < Math.min(toks.length, vi + 6); i++) {
      for (let k = 0; k < words.length; k++) {
        if (near(toks[i], words[k])) return PARTS[words[k]]
      }
    }
  }
  if (/\b(?:step|walk|stand|get)\w*\s+(?:into|in|under|inside)\s+the\s+(?:body\s+)?scanner\b/.test(normText(text))) return 'all'
  return ''
}

function extraAI(s) {
  const parts = [], L = s.lact
  if (lactActive(s) || L.stored > 1) parts.push('Milk ' + Math.round(L.stored / Math.max(1, milkCap(s)) * 100) + '% full' + (lactActive(s) ? ', lactating' : ''))
  const mf = fillOf(s, REGIONS)
  if (mf > 0.05) parts.push('Mana ' + Math.round(mf * 100) + '%')
  const cs = []
  if (s.curses.hunger) cs.push('hunger')
  if (s.curses.leech) cs.push('mana leech (' + RWORD[s.curses.leech] + ')')
  if (s.curses.forced) cs.push('forced milk')
  if (s.curses.bias) cs.push('growth bias (' + RWORD[s.curses.bias] + ')')
  if (cs.length) parts.push('Cursed: ' + cs.join(', '))
  return parts.length ? ' ' + parts.join('. ') + '.' : ''
}
function aiSummary(s, label) {
  const m = measures(s), a = abilities(s, m), c = chestCalc(s)
  return (label ? label : 'Body') + ': ' + r1(m.height) + ' cm, ' + r1(m.weight) + ' kg, ' + Math.round(m.bodyfat) + '% fat, bra ' + cup(m) + '. ' + (CFG.DESCRIBE ? describeLook(s, m) + '. ' : '') + (aiLine(s) === 'No notable changes yet' ? '' : aiLine(s) + '. ') +
    'Chest: about ' + Math.round(c.V.total) + ' cc each, ' + firmWord(c.firm) + ', ' + sagWord(s.sag) +
    '.' + extraAI(s) + ' Ate ' + fmt(s.eaten || 0) + ' of ' + fmt(need(s, m, s.burned)) + ' kcal today. Stats: ' + statLine(a) + '.'
}
function refreshMemory(recent) {
  const s = state.bt
  state.memory = state.memory || {}
  let note = state.bt_hideYou ? '' : '[' + aiSummary(s) + ']'
  // other tracked characters are described only while their name is in the recent story
  const mentioned = namesIn(recent || '')
  if (state.bt_hideYou && defKey() && mentioned.indexOf(defKey()) < 0) mentioned.unshift(defKey())   // the main character is always described
  mentioned.slice(0, CFG.NPC_MAX).forEach((k) => { note += ' [' + aiSummary(state.npcs[k], state.npcs[k].name) + ']' })
  if (note) note += ' [Never invent body measurements or changes; use only these numbers.]'
  if (state.bt_inspect) {
    const who = state.bt_inspectWho || '', t = sheetOf(who)
    if (t) note += ' [Describe this in detail using only these facts: ' + (who ? t.name + ': ' : '') + inspectPart(t, state.bt_inspect) + ']'
  }
  // the tag reminder: short, and by default inside the Author's Note rather than the last line of the context, where the AI copies it most
  let tags = ''
  if (CFG.TAG_HELP) {
    const F = CFG.FEATURES
    tags = TAG_MARK + ', never mention: after eating, exercise or sleep end with: [ate 600] [burn 300] [train legs 2] [day] [gland +20]'
    if (F.milk) tags += ' [milk -300]'
    if (F.mana) tags += ' [mana +30 arms]'
    if (F.curses) tags += ' [curse add hunger]'
    tags += '.'
    const names = npcKeys().map((k) => state.npcs[k].name)
    if (names.length) tags += ' Others: name last, [ate 300 ' + names[0] + '].'
    tags += ']'
  }
  if (CFG.TAG_PLACE === 'front') {   // the very end of the context (strongest, but most likely to be echoed)
    state.memory.authorsNote = note.trim()
    state.memory.frontMemory = tags
  } else {
    state.memory.authorsNote = (note + ' ' + tags).trim()
    state.memory.frontMemory = ''
  }
}
function sheetText(s, label) {
  const m = measures(s), a = abilities(s, m), c = chestCalc(s)
  const list = (o) => REGIONS.map((r) => r + ' ' + r1(o[r])).join(', ')
  return 'BODY SHEET' + (label ? ': ' + label : '') + ' (updated by the script)\n' +
    'Day: ' + s.day + '\n' +
    'Height: ' + r1(m.height) + ' cm\n' +
    'Weight: ' + r1(m.weight) + ' kg\n' +
    'Body fat: ' + r1(m.bodyfat) + ' %\n' +
    'Bust: ' + r1(m.bust) + ' cm\n' +
    'Underbust: ' + r1(m.underbust) + ' cm\n' +
    'Waist: ' + r1(m.waist) + ' cm\n' +
    'Hips: ' + r1(m.hips) + ' cm\n' +
    'Arm: ' + r1(m.arm) + ' cm\n' +
    'Thigh: ' + r1(m.thigh) + ' cm\n' +
    'Bra: ' + cup(m) + '\n' +
    describeLook(s, m) + '\n' +
    'Glandular cc: ' + r1(s.gland) + '\n' +
    'Breast cc each: ' + Math.round(c.V.total) + ' (fat ' + Math.round(c.V.fat) + ')\n' +
    'Firmness: ' + Math.round(c.firm) + '\n' +
    'Sag: ' + r1(s.sag) + '\n' +
    'Potential cc: ' + r1(s.glandMax) + '\n' +
    'Milk ml: ' + Math.round(s.lact.stored) + ' / ' + Math.round(milkCap(s)) + ' (' + (lactActive(s) ? 'lactating' : 'not lactating') + ', supply ' + Math.round(s.lact.sup * 100) + '%)\n' +
    'Mana: ' + Math.round(REGIONS.reduce((t, r) => t + s.mana[r], 0)) + ' / ' + Math.round(REGIONS.reduce((t, r) => t + manaCap(s, r), 0)) + '\n' +
    'Curses: ' + ([s.curses.hunger && 'hunger', s.curses.leech && 'leech ' + s.curses.leech, s.curses.forced && 'forced milk', s.curses.bias && 'bias ' + s.curses.bias].filter(Boolean).join(', ') || 'none') + '\n' +
    'Stats: ' + statLine(a) + '\n' +
    'Muscle kg: ' + list(s.mus) + '\n' +
    'Fat kg: ' + list(s.fat) + '\n' +
    'Kcal today: ' + fmt(s.eaten || 0) + ' / ' + fmt(need(s, m, s.burned))
}
function sheetLine(s, label) {
  const m = measures(s), a = abilities(s, m)
  return (label ? label + ' | ' : '') + 'Day ' + s.day + ' | ' + r1(m.height) + ' cm, ' + r1(m.weight) + ' kg, ' + r1(m.bodyfat) + '% fat | bra ' + cup(m) +
    ', ' + Math.round(volume(s).total) + ' cc each | ' + statLine(a) + ' | ' + fmt(s.eaten || 0) + '/' + fmt(need(s, m, s.burned)) + ' kcal'
}
function statusLine(notes) {
  let touched = (state.bt_touched && state.bt_touched.length) ? state.bt_touched : [defKey()]
  touched = touched.filter((k, i) => touched.indexOf(k) === i && sheetOf(k))
  if (!touched.length) touched = [defKey()]
  const lines = touched.map((k) => '[' + sheetLine(sheetOf(k), nameOf(k)))
  let first = lines[0]
  if (state.bt_note) first += ' | ' + state.bt_note
  if (notes && notes.length) first += ' | ' + notes.join(', ')
  lines[0] = first
  let t = lines.map((l) => l + ']').join('\n')
  if (state.bt_help) t += '\n' + HELP
  return t
}

// ---------- story card mirror ----------
function writeCard() {
  const cards = typeof storyCards !== 'undefined' ? storyCards : []
  const put = (keys, entry) => {
    let idx = -1
    for (let i = 0; i < cards.length; i++) { if (cards[i].type === CARD_TYPE && cards[i].keys === keys) { idx = i; break } }
    if (idx === -1) addStoryCard(keys, entry, CARD_TYPE)
    else updateStoryCard(idx, keys, entry, CARD_TYPE)
  }
  if (!state.bt_hideYou) {
    const entry = sheetText(state.bt)
    put(CARD_KEYS, entry)
    state.bt_cardPrev = state.bt_card
    state.bt_card = entry
  } else if (typeof removeStoryCard === 'function') {   // your own sheet is hidden: take its card away
    for (let i = cards.length - 1; i >= 0; i--) { if (cards[i].type === CARD_TYPE && cards[i].keys === CARD_KEYS) removeStoryCard(i) }
  }
  npcKeys().forEach((k) => put(CARD_KEYS + '-' + k, sheetText(state.npcs[k], state.npcs[k].name)))
  // drop cards of characters that were removed
  if (typeof removeStoryCard === 'function') {
    for (let i = cards.length - 1; i >= 0; i--) {
      const kk = cards[i].keys
      if (cards[i].type === CARD_TYPE && typeof kk === 'string' && kk.indexOf(CARD_KEYS + '-') === 0 && !state.npcs[kk.slice(CARD_KEYS.length + 1)]) removeStoryCard(i)
    }
  }
}
const CARD_LINES = { 'height': 'height', 'weight': 'weight', 'body fat': 'bodyfat', 'bust': 'bust', 'underbust': 'underbust', 'waist': 'waist', 'hips': 'hips', 'arm': 'arm', 'thigh': 'thigh', 'glandular cc': 'gland', 'potential cc': 'potential', 'sag': 'sag' }
function cardValues(str) {
  const out = {}
  String(str).split('\n').forEach((line) => {
    const m = line.match(/^([A-Za-z ]+):\s*(-?\d+(?:\.\d+)?)/)
    if (m && CARD_LINES[m[1].trim().toLowerCase()]) out[CARD_LINES[m[1].trim().toLowerCase()]] = parseFloat(m[2])
  })
  return out
}
// ---------- Player setup card (custom build): fill in your own sheet by editing one story card ----------
// Created once on the first turn with a blank template. When its text differs from what was last applied, the values are
// applied to your sheet (rebuilt like :sheet add while nothing has happened yet, otherwise like :set), once per edit.
// Blank values keep the default, a bad value is skipped and named in the status line. The keys never appear in the story.
const SETUP_TYPE = 'Player setup', SETUP_KEYS = 'playersetup'
const SETUP_TEMPLATE = 'name= height= weight= bodyfat= underbust= bust= waist= hips= pattern=even look=athletic gland= potential='
function playerPristine(s) {   // nothing has happened to this sheet yet
  return s.day === 1 && s.eaten === null && !s.burned && REGIONS.every((r) => !s.train[r]) && !s.fuelLog.length && AB.every((a) => !s.bonus[a]) &&
    MEAS.every((m) => !s.adj[m]) && s.gland === s.gland0 && s.glandMax === s.start.potential && !s.sag && !s.lact.on
}
function applyPlayerCard() {
  const cards = typeof storyCards !== 'undefined' && storyCards ? storyCards : []
  let entry = null
  for (let i = 0; i < cards.length; i++) { if (cards[i].type === SETUP_TYPE && cards[i].keys === SETUP_KEYS) { entry = String(cards[i].entry || ''); break } }
  if (entry === null) {
    if (state.bt_setupMade) return   // you deleted it: it is not made again
    entry = (state.bt && state.bt.seedCard) || SETUP_TEMPLATE   // after seeding from the placeholders, the card shows those values
    addStoryCard(SETUP_KEYS, entry, SETUP_TYPE)
    if (state.bt.seedCard) state.bt.cardApplied = entry   // already applied
  }
  state.bt_setupMade = true
  const s = state.bt
  if (s.cardApplied === entry) return   // unchanged since last time: do not apply again (later :set changes stay)
  const r = parseSheetOpts(entry, true)
  const did = Object.keys(r.st).concat(Object.keys(r.o))
  if (did.length) {
    if (playerPristine(s)) {   // rebuild exactly like :sheet add would
      const n = newBT(Object.assign({}, s.start, r.st), { name: r.o.name || s.name, pattern: r.o.pattern || s.pattern, look: r.o.look || s.look, muscle: s.muscleMul, activity: s.activity })
      n.pace = s.pace; n.paceSet = s.paceSet; n.support = s.support
      state.bt = n
    } else {   // the story has moved on: the same as typing :set for each value
      Object.keys(r.st).forEach((k) => setValue(s, k, r.st[k]))
      if (r.o.pattern) s.pattern = r.o.pattern
      if (r.o.look) s.look = r.o.look
      if (r.o.name) s.name = r.o.name
    }
  }
  state.bt.cardApplied = entry
  const notes = []
  if (did.length && entry !== SETUP_TEMPLATE) notes.push('Player setup applied: ' + (did.length > 4 ? did.length + ' values' : did.join(', ')))
  if (r.bad.length) notes.push('Player setup skipped: ' + r.bad.join(' '))
  state.bt_cardNote = [state.bt_cardNote].concat(notes).filter(Boolean).join(' | ')
}
function readCard() {
  state.bt_cardNote = ''
  if (CFG.PLACEHOLDERS) seedFromPlaceholders()
  if (CFG.PLAYER_CARD) applyPlayerCard()
  if (!CFG.CARD_READBACK || !state.bt_card) return
  const cards = typeof storyCards !== 'undefined' ? storyCards : []
  for (let i = 0; i < cards.length; i++) {
    if (cards[i].type !== CARD_TYPE) continue
    const entry = cards[i].entry
    if (entry === state.bt_card || entry === state.bt_cardPrev) return   // unchanged (or our write is still catching up)
    const was = cardValues(state.bt_card), now = cardValues(entry)
    Object.keys(now).forEach((k) => { if (was[k] !== undefined && Math.abs(now[k] - was[k]) > 0.049) setValue(state.bt, k, now[k]) })
    return
  }
}

// ---------- :probe (custom build only): what do the hooks receive? ----------
// Writes one story card with keys "probe" listing info, the names of the state keys, any state that looks like
// character/player info, history[0] and the last two history entries in full, and the other story cards.
// It changes no sheet. Read it in AI Dungeon's story card list (type "Probe"), then delete it.
function probeCard() {
  const cut = (v, n) => {
    let t
    try { t = typeof v === 'string' ? v : JSON.stringify(v) } catch (e) { t = String(v) }
    if (t === undefined) return 'undefined'
    return t.length > n ? t.slice(0, n) + '...(+' + (t.length - n) + ' more characters)' : t
  }
  const L = ['PROBE written at action ' + turnNo()]
  L.push('', '--- info (key = value) ---')
  if (typeof info !== 'undefined' && info) Object.keys(info).forEach((k) => L.push(k + ' = ' + cut(info[k], 300)))
  else L.push('info is missing')
  L.push('', '--- state keys (names only) ---', Object.keys(state).join(', '))
  if (state.memory && typeof state.memory === 'object') L.push('state.memory keys: ' + Object.keys(state.memory).join(', '))
  L.push('', '--- does state hold character or player info? ---')
  const guess = ['character', 'player', 'name', 'characterName', 'playerName', 'you', 'class', 'hero', 'persona', 'user', 'protagonist']
  guess.forEach((k) => L.push('state.' + k + ': ' + (state[k] === undefined ? 'absent' : 'PRESENT = ' + cut(state[k], 300))))
  Object.keys(state).filter((k) => /char|player|name|class|hero|persona|user|protag/i.test(k) && guess.indexOf(k) < 0).forEach((k) => L.push('state.' + k + ' (found by name) = ' + cut(state[k], 300)))
  L.push('', '--- state.placeholders (full) ---')
  L.push(state.placeholders === undefined || state.placeholders === null ? 'none' : (Array.isArray(state.placeholders) ? 'array of ' + state.placeholders.length + ': ' : typeof state.placeholders + ': ') + cut(state.placeholders, 4000))
  const H = typeof history !== 'undefined' && history ? history : []
  L.push('', '--- history: ' + H.length + ' entries ---')
  const shown = []
  ;[0, H.length - 2, H.length - 1].forEach((i) => {
    const a = H[i]
    if (!a || shown.indexOf(i) >= 0) return
    shown.push(i)
    const txt = typeof a.text === 'string' ? a.text : ''
    L.push('', 'history[' + i + '] type=' + a.type + ', length=' + txt.length + ', fields=' + Object.keys(a).join(','), txt)
  })
  const cards = typeof storyCards !== 'undefined' && storyCards ? storyCards : []
  L.push('', '--- story cards: ' + cards.length + ' (type | keys | start of entry) ---')
  cards.forEach((c) => { if (c.keys !== 'probe') L.push((c.type || '') + ' | ' + c.keys + ' | ' + cut(String(c.entry || '').slice(0, 160), 160)) })
  const entry = L.join('\n')
  let idx = -1
  for (let i = 0; i < cards.length; i++) { if (cards[i].keys === 'probe') { idx = i; break } }
  if (idx === -1) addStoryCard('probe', entry, 'Probe')
  else updateStoryCard(idx, 'probe', entry, 'Probe')
  return 'Probe card written (story card "probe")'
}

// ---------- seeding your sheet from state.placeholders (custom build) ----------
// AI Dungeon fills state.placeholders (an array of { question, answer }) once, when the adventure starts. On the first turn the
// answers set up YOUR sheet, once, and only while nothing has happened to it yet. A missing, empty or unreadable answer keeps the
// default; if no placeholders exist (or none match) nothing happens. The "seeded" mark lives on the sheet, so it is part of the
// undo/retry snapshots: a replayed first turn seeds once, and later :set changes are never overwritten.
const PH_BUILD = { slim: [18, 'even', 'athletic'], average: [24, 'even', 'off'], curvy: [32, 'pear', 'curvy'], athletic: [16, 'even', 'athletic'] }   // body fat %, fat pattern, look
const PH_ACTIVITY = { couch: { activity: 1.2, muscle: 0.85 }, active: {}, runner: { activity: 1.5, muscle: 1.1 } }   // activity factor, starting muscle multiplier
const PH_CHEST = { small: [60, 150], average: [90, 200], large: [130, 300] }   // glandular cc, potential cc
const PH_WORDS = { slim: ['skinny', 'thin'], average: ['medium', 'normal', 'avg'], curvy: ['thick'], athletic: ['fit', 'toned'], couch: ['sedentary', 'lazy'], runner: ['running'], small: ['tiny', 'flat'], large: ['big', 'huge'] }   // other words that mean the same

function phAnswers() {   // the answers by field, or null when there are no placeholders
  const ph = state.placeholders
  if (!ph || typeof ph !== 'object') return null
  const list = Array.isArray(ph) ? ph : Object.keys(ph).map((k) => ({ question: k, answer: ph[k] }))
  const out = {}
  list.forEach((p) => {
    if (!p || p.question === undefined || p.answer === undefined || p.answer === null) return
    const q = String(p.question).toLowerCase().replace(/\s+/g, ' ').trim(), a = String(p.answer).replace(/\s+/g, ' ').trim()
    if (!a) return
    const f = /^(?:character\.)?name\b/.test(q) ? 'name' : /^(?:character\.)?gender\b/.test(q) ? 'gender' : /^height/.test(q) ? 'height' : /^weight/.test(q) ? 'weight'
      : /^build/.test(q) ? 'build' : /^activity/.test(q) ? 'activity' : /^chest/.test(q) ? 'chest' : ''
    if (f && out[f] === undefined) out[f] = a
  })
  return out
}
function phHeight(a) {   // "170", "170cm", "1.70 m", "5'7", "5 ft 7 in", "67 in" -> cm, kept within 120-230; null if there is no number
  const s = a.toLowerCase().replace(/[’′]/g, "'").replace(/[”″]/g, '"')
  let cm = null, m
  if ((m = s.match(/(\d+(?:\.\d+)?)\s*cm\b/))) cm = parseFloat(m[1])
  else if ((m = s.match(/(\d+(?:\.\d+)?)\s*(?:'|ft(?![a-z])|feet\b|foot\b)\s*(\d+(?:\.\d+)?)?/))) cm = parseFloat(m[1]) * 30.48 + (m[2] ? parseFloat(m[2]) * 2.54 : 0)
  else if ((m = s.match(/(\d+(?:\.\d+)?)\s*(?:in|inch|inches)\b/))) cm = parseFloat(m[1]) * 2.54
  else if ((m = s.match(/(\d+(?:\.\d+)?)\s*m(?:eters?|etres?)?\b/))) cm = parseFloat(m[1]) * 100
  else if ((m = s.match(/\d+(?:\.\d+)?/))) { const n = parseFloat(m[0]); cm = n <= 3 ? n * 100 : n <= 8 ? n * 30.48 : n }   // 1.7 = metres, 5.7 = feet, 170 = cm
  return cm !== null && cm > 0 ? r1(clampN(cm, 120, 230)) : null
}
function phWeight(a) {   // "60", "60 kg", "130 lb", "9 st 7" -> kg, kept within 30-250; null if there is no number
  const s = a.toLowerCase()
  let kg = null, m
  if ((m = s.match(/(\d+(?:\.\d+)?)\s*(?:st|stone)\b\s*(?:(\d+(?:\.\d+)?)\s*(?:lb|lbs|pounds?)?)?/))) kg = parseFloat(m[1]) * 6.35029 + (m[2] ? parseFloat(m[2]) * 0.453592 : 0)
  else if ((m = s.match(/(\d+(?:\.\d+)?)\s*(?:lb|lbs|pounds?)\b/))) kg = parseFloat(m[1]) * 0.453592
  else if ((m = s.match(/\d+(?:\.\d+)?/))) kg = parseFloat(m[0])
  return kg !== null && kg > 0 ? r1(clampN(kg, 30, 250)) : null
}
function phPick(answer, keys) {   // which of the words the answer says (typos allowed, the earliest one wins), or null
  const toks = tokensOf(answer)
  let best = null, at = 1e9
  keys.forEach((key) => {
    ;[key].concat(PH_WORDS[key] || []).forEach((w) => {
      const i = findTok(toks, [w])
      if (i >= 0 && i < at) { at = i; best = key }
    })
  })
  return best
}
function seedFromPlaceholders() {
  const s = state.bt
  if (!CFG.PLACEHOLDERS || state.bt_hideYou || !s || s.seeded) return
  const a = phAnswers()
  if (!a) return
  const st = {}, o = {}, said = []
  const nm = a.name !== undefined ? (a.name.match(/[A-Za-z][\w-]*/) || [''])[0] : ''   // one word, and not a character that already exists
  if (nm && !state.npcs[nm.toLowerCase()]) o.name = nm
  const gender = a.gender !== undefined ? a.gender.slice(0, 20) : ''
  const h = a.height !== undefined ? phHeight(a.height) : null
  if (h) { st.height = h; said.push(h + ' cm') }
  const w = a.weight !== undefined ? phWeight(a.weight) : null
  if (w) { st.weight = w; said.push(w + ' kg') }
  const b = a.build !== undefined ? phPick(a.build, ['slim', 'average', 'curvy', 'athletic']) : null
  if (b) { st.bodyfat = PH_BUILD[b][0]; o.pattern = PH_BUILD[b][1]; o.look = PH_BUILD[b][2]; said.push(b) }
  const act = a.activity !== undefined ? phPick(a.activity, ['couch', 'active', 'runner']) : null
  if (act) { Object.assign(o, PH_ACTIVITY[act]); said.push(act) }
  const ch = a.chest !== undefined ? phPick(a.chest, ['small', 'average', 'large']) : null
  if (ch) { st.gland = PH_CHEST[ch][0]; st.potential = PH_CHEST[ch][1]; said.push(ch + ' chest') }
  if (!o.name && !gender && !said.length) return   // nothing usable: do nothing
  if (!playerPristine(s)) { s.seeded = true; return }   // the story has already moved on: never overwrite it
  const n = newBT(Object.assign({}, s.start, st), { name: o.name || s.name, pattern: o.pattern || s.pattern, look: o.look || s.look, muscle: o.muscle, activity: o.activity })
  n.pace = s.pace; n.paceSet = s.paceSet; n.support = s.support
  if (gender) n.gender = gender   // remembered only, no stat changes
  n.seeded = true
  const v = (x) => (x === undefined ? '' : x)
  n.seedCard = 'name=' + (o.name || '') + ' height=' + v(st.height) + ' weight=' + v(st.weight) + ' bodyfat=' + v(st.bodyfat) + ' underbust= bust= waist= hips= pattern=' + n.pattern + ' look=' + n.look + ' gland=' + v(st.gland) + ' potential=' + v(st.potential)
  state.bt = n
  if (said.length) state.bt_cardNote = 'Player sheet set from your answers: ' + said.join(', ') + '.'
}
