// Builds the Library tab scripts: node build.js
// AI Dungeon has no import/export, so everything is one shared scope. The order below is the load order
// (top-level const values are used while loading, so a module may only use names from modules above it).
const fs = require('fs')
const path = require('path')
const dir = __dirname

const ORDER = [
  'src/01_config.js', 'src/02_constants.js', 'src/03_helpers.js', 'src/04_state.js', 'src/05_characters_undo.js',
  'src/06_body_model.js', 'src/07_energy_growth.js', 'src/08_set_values.js', 'src/09_ai_tags.js', 'src/10_detect_typed.js',
  'src/11_commands.js', 'src/12_ai_text_status.js', 'src/13_look_words.js', 'src/14_inspect.js', 'src/15_story_card.js'
]
const BUILDS = [   // output file, preset inserted right after the config (or null)
  { out: 'bt_library.js', preset: null, title: 'LIBRARY tab' },
  { out: 'bt_library_whitney.js', preset: 'presets/whitney.js', title: 'LIBRARY tab (Whitney preset)' }
]

const read = (f) => fs.readFileSync(path.join(dir, f), 'utf8').replace(/\r/g, '').replace(/\n*$/, '\n')

// a name declared at the top level of two modules would be a redeclaration error once concatenated
const seen = {}
ORDER.forEach((f) => {
  read(f).split('\n').forEach((line) => {
    const m = line.match(/^(?:const|let|var|function)\s+([A-Za-z_$][\w$]*)/)
    if (!m) return
    if (seen[m[1]]) throw new Error('Name "' + m[1] + '" is declared in both ' + seen[m[1]] + ' and ' + f)
    seen[m[1]] = f
  })
})

BUILDS.forEach((b) => {
  const parts = ORDER.map((f, i) => (i === 1 && b.preset ? read(b.preset) + '\n' : '') + read(f))
  const head = '// ============================================================\n// BODY TRACKER for AI Dungeon: ' + b.title + '\n// GENERATED by build.js from src/' + (b.preset ? ' and ' + b.preset : '') + '. Edit those, not this file.\n// Paste this whole file into the Library tab.\n// ============================================================\n\n'
  fs.writeFileSync(path.join(dir, b.out), head + parts.join('\n'))
  console.log('built ' + b.out)
})
